# Generated by Django 3.1.13 on 2021-08-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biserici", "0044_auto_20210803_1738"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="componentaartistica",
            name="iconostas_pronaos_naos_detalii",
        ),
        migrations.RemoveField(
            model_name="componentaartistica",
            name="iconostas_pronaos_naos_material",
        ),
        migrations.RemoveField(
            model_name="componentaartistica",
            name="iconostas_pronaos_naos_numar_intrari",
        ),
        migrations.RemoveField(
            model_name="componentaartistica",
            name="iconostas_pronaos_naos_tehnica",
        ),
        migrations.RemoveField(
            model_name="componentaartistica",
            name="iconostas_pronaos_naos_tip",
        ),
        migrations.RemoveField(
            model_name="historicalcomponentaartistica",
            name="iconostas_pronaos_naos_detalii",
        ),
        migrations.RemoveField(
            model_name="historicalcomponentaartistica",
            name="iconostas_pronaos_naos_material",
        ),
        migrations.RemoveField(
            model_name="historicalcomponentaartistica",
            name="iconostas_pronaos_naos_numar_intrari",
        ),
        migrations.RemoveField(
            model_name="historicalcomponentaartistica",
            name="iconostas_pronaos_naos_tip",
        ),
    ]
