# Generated by Django 3.1.13 on 2022-07-21 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("biserici", "0069_auto_20220721_1420"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fragmente", "0008_auto_20220720_2038"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProportiePicturaMurala",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("nume", models.CharField(max_length=300)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical proportie pictura murala",
                "verbose_name_plural": "historical Proporție Pictură Murală",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTehnicaPicturiiDecoratieiMuraleExterioare",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("nume", models.CharField(max_length=300)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical tehnica picturii decoratiei murale exterioare",
                "verbose_name_plural": "historical Tehnica Picturii Decorației Murale Exterioare",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTehnicaPicturiiDecoratieiMuraleInterioare",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("nume", models.CharField(max_length=300)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical tehnica picturii decoratiei murale interioare",
                "verbose_name_plural": "historical Tehnica Picturii Decorației Murale Interioare",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ProportiePicturaMurala",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nume", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name_plural": "Proporție Pictură Murală",
                "ordering": ["nume"],
            },
        ),
        migrations.CreateModel(
            name="TehnicaPicturiiDecoratieiMuraleExterioare",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nume", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name_plural": "Tehnica Picturii Decorației Murale Exterioare",
                "ordering": ["nume"],
            },
        ),
        migrations.CreateModel(
            name="TehnicaPicturiiDecoratieiMuraleInterioare",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nume", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name_plural": "Tehnica Picturii Decorației Murale Interioare",
                "ordering": ["nume"],
            },
        ),
        migrations.RenameModel(
            old_name="ElementeComponenteIconostas",
            new_name="ComponenteIconostas",
        ),
        migrations.RenameModel(
            old_name="HistoricalElementeComponenteIconostas",
            new_name="HistoricalComponenteIconostas",
        ),
        migrations.RemoveField(
            model_name="historicaltehnicapicturiidecoratieimurale",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="TehnicaPicturiiDecoratieiMurale",
        ),
        migrations.AlterModelOptions(
            name="componenteiconostas",
            options={"ordering": ["nume"], "verbose_name_plural": "Componente Iconostas"},
        ),
        migrations.AlterModelOptions(
            name="historicalcomponenteiconostas",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical componente iconostas",
                "verbose_name_plural": "historical Componente Iconostas",
            },
        ),
        migrations.DeleteModel(
            name="HistoricalTehnicaPicturiiDecoratieiMurale",
        ),
    ]
