# Generated by Django 3.1.13 on 2021-07-29 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("biserici", "0003_auto_20210729_1827"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nomenclatoare", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalElementeBiserica",
            new_name="HistoricalElementBiserica",
        ),
        migrations.AlterModelOptions(
            name="historicalelementbiserica",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical element biserica",
            },
        ),
        migrations.RenameModel(
            old_name="ElementeBiserica",
            new_name="ElementBiserica",
        ),
        migrations.CreateModel(
            name="PovesteBiserica",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("detalii", models.TextField()),
                ("sursa", models.TextField()),
                ("istoric", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="biserici.istoric")),
            ],
            options={
                "verbose_name_plural": "Povești Biserică",
            },
        ),
        migrations.CreateModel(
            name="InterventieBiserica",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("datat", models.BooleanField(default=False)),
                ("an", models.IntegerField(blank=True, null=True)),
                ("observatii", models.TextField(blank=True, null=True)),
                ("sursa", models.TextField(blank=True, null=True)),
                ("este_ultima_interventie", models.BooleanField(default=False)),
                (
                    "element",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="nomenclatoare.elementbiserica"),
                ),
                ("istoric", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="biserici.istoric")),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPovesteBiserica",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("detalii", models.TextField()),
                ("sursa", models.TextField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "istoric",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.istoric",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical poveste biserica",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
