# Generated by Django 3.1.13 on 2021-10-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nomenclatoare", "0014_historicalmaterialestructura_materialestructura"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amplasamentbiserica",
            options={"ordering": ["nume"], "verbose_name_plural": "Amplasamente Biserică"},
        ),
        migrations.AlterModelOptions(
            name="amplasareturn",
            options={"ordering": ["nume"], "verbose_name_plural": "Amplasări Turn"},
        ),
        migrations.AlterModelOptions(
            name="asezaretalpaturn",
            options={"ordering": ["nume"], "verbose_name_plural": "Așezări talpă turn"},
        ),
        migrations.AlterModelOptions(
            name="boltapestealtar",
            options={"ordering": ["nume"], "verbose_name_plural": "Bolți peste altar"},
        ),
        migrations.AlterModelOptions(
            name="comuna",
            options={"ordering": ["nume"], "verbose_name_plural": "Comune"},
        ),
        migrations.AlterModelOptions(
            name="ctitorbiserica",
            options={"verbose_name_plural": "Ctitori"},
        ),
        migrations.AlterModelOptions(
            name="cultbiserica",
            options={"ordering": ["nume"], "verbose_name_plural": "Culturi Biserică"},
        ),
        migrations.AlterModelOptions(
            name="decorturn",
            options={"ordering": ["nume"], "verbose_name_plural": "Decoruri Turn"},
        ),
        migrations.AlterModelOptions(
            name="detaliupodturn",
            options={"ordering": ["nume"], "verbose_name_plural": "Detalii podul turnului"},
        ),
        migrations.AlterModelOptions(
            name="dimensiuneturn",
            options={"ordering": ["nume"], "verbose_name_plural": "Dimensiuni Turn"},
        ),
        migrations.AlterModelOptions(
            name="elementansambluconstruit",
            options={"ordering": ["nume"], "verbose_name_plural": "Elemente Ansamblu Construit"},
        ),
        migrations.AlterModelOptions(
            name="elementbiserica",
            options={"ordering": ["nume"], "verbose_name_plural": "Elemente Biserica"},
        ),
        migrations.AlterModelOptions(
            name="elementimportant",
            options={"ordering": ["nume"], "verbose_name_plural": "Elemente Importante"},
        ),
        migrations.AlterModelOptions(
            name="esentalemnoasa",
            options={"ordering": ["nume"], "verbose_name_plural": "Esenta Lemnoasa"},
        ),
        migrations.AlterModelOptions(
            name="eveniment",
            options={"ordering": ["nume"], "verbose_name_plural": "Evenimente"},
        ),
        migrations.AlterModelOptions(
            name="evenimentbiserica",
            options={"verbose_name_plural": "Evenimente Istorice"},
        ),
        migrations.AlterModelOptions(
            name="finisaj",
            options={"ordering": ["nume"], "verbose_name_plural": "Finisaj"},
        ),
        migrations.AlterModelOptions(
            name="finisajexterior",
            options={"ordering": ["nume"], "verbose_name_plural": "Finisaj Exterior"},
        ),
        migrations.AlterModelOptions(
            name="finisajiconostas",
            options={"ordering": ["nume"], "verbose_name_plural": "Finisaje Iconostas"},
        ),
        migrations.AlterModelOptions(
            name="formasarpanteturle",
            options={"ordering": ["nume"], "verbose_name_plural": "Forme șarpante turle"},
        ),
        migrations.AlterModelOptions(
            name="functiunebiserica",
            options={"ordering": ["nume"], "verbose_name_plural": "Funcțiuni Biserică"},
        ),
        migrations.AlterModelOptions(
            name="galerieturn",
            options={"ordering": ["nume"], "verbose_name_plural": "Galerii Turn"},
        ),
        migrations.AlterModelOptions(
            name="judet",
            options={"ordering": ["nume"], "verbose_name_plural": "Județe"},
        ),
        migrations.AlterModelOptions(
            name="localitate",
            options={"ordering": ["nume"], "verbose_name_plural": "Localități"},
        ),
        migrations.AlterModelOptions(
            name="localizarepictura",
            options={"ordering": ["nume"], "verbose_name_plural": "Localizări Pictură"},
        ),
        migrations.AlterModelOptions(
            name="material",
            options={"ordering": ["nume"], "verbose_name_plural": "Materiale"},
        ),
        migrations.AlterModelOptions(
            name="materialestructura",
            options={"ordering": ["nume"], "verbose_name_plural": "Materiale Structura"},
        ),
        migrations.AlterModelOptions(
            name="materialfinisajpardoseli",
            options={"ordering": ["nume"], "verbose_name_plural": "Material Finisaj Pardoseli"},
        ),
        migrations.AlterModelOptions(
            name="materialfinisajperetiinteriori",
            options={"ordering": ["nume"], "verbose_name_plural": "Material Finisaj Pereti Interiori"},
        ),
        migrations.AlterModelOptions(
            name="materialinvelitoareturle",
            options={"ordering": ["nume"], "verbose_name_plural": "Material învelitoare turle"},
        ),
        migrations.AlterModelOptions(
            name="mesterbiserica",
            options={"verbose_name_plural": "Meșteri"},
        ),
        migrations.AlterModelOptions(
            name="mobilier",
            options={"ordering": ["nume"], "verbose_name_plural": "Mobilier"},
        ),
        migrations.AlterModelOptions(
            name="obiectcult",
            options={"ordering": ["nume"], "verbose_name_plural": "Obiecte Cult"},
        ),
        migrations.AlterModelOptions(
            name="peisagisticasit",
            options={"ordering": ["nume"], "verbose_name_plural": "Peisagistică Sit"},
        ),
        migrations.AlterModelOptions(
            name="persoana",
            options={"ordering": ["nume"], "verbose_name_plural": "Persoane"},
        ),
        migrations.AlterModelOptions(
            name="planimetrie",
            options={"ordering": ["nume"], "verbose_name_plural": "Planimetrii"},
        ),
        migrations.AlterModelOptions(
            name="planturn",
            options={"ordering": ["nume"], "verbose_name_plural": "Planuri Turn"},
        ),
        migrations.AlterModelOptions(
            name="pozitionareturle",
            options={"ordering": ["nume"], "verbose_name_plural": "Poziționare turle"},
        ),
        migrations.AlterModelOptions(
            name="proprietatebiserica",
            options={"ordering": ["nume"], "verbose_name_plural": "Proprietăți Biserică"},
        ),
        migrations.AlterModelOptions(
            name="registruiconostas",
            options={"ordering": ["nume"], "verbose_name_plural": "Registre Iconostas"},
        ),
        migrations.AlterModelOptions(
            name="relatiecimitir",
            options={"ordering": ["nume"], "verbose_name_plural": "Relație Cimitir"},
        ),
        migrations.AlterModelOptions(
            name="relatietalpaturn",
            options={"ordering": ["nume"], "verbose_name_plural": "Relații talpă turn"},
        ),
        migrations.AlterModelOptions(
            name="secol",
            options={"ordering": ["nume"], "verbose_name_plural": "Secole"},
        ),
        migrations.AlterModelOptions(
            name="singularitatebiserica",
            options={"ordering": ["nume"], "verbose_name_plural": "Singularități Biserică"},
        ),
        migrations.AlterModelOptions(
            name="statutbiserica",
            options={"ordering": ["nume"], "verbose_name_plural": "Statuturi Biserică"},
        ),
        migrations.AlterModelOptions(
            name="studiu",
            options={"ordering": ["nume"], "verbose_name_plural": "Studii"},
        ),
        migrations.AlterModelOptions(
            name="studiudendocronologic",
            options={"ordering": ["nume"], "verbose_name_plural": "Studii dendocronologice"},
        ),
        migrations.AlterModelOptions(
            name="studiuistoric",
            options={"ordering": ["nume"], "verbose_name_plural": "tudii Istorice"},
        ),
        migrations.AlterModelOptions(
            name="suportpictura",
            options={"ordering": ["nume"], "verbose_name_plural": "Suport Pictură"},
        ),
        migrations.AlterModelOptions(
            name="sursadatare",
            options={"ordering": ["nume"], "verbose_name_plural": "Surse Datări"},
        ),
        migrations.AlterModelOptions(
            name="tehnicapictura",
            options={"ordering": ["nume"], "verbose_name_plural": "Tehnici Pictura"},
        ),
        migrations.AlterModelOptions(
            name="tiparcbolta",
            options={"ordering": ["nume"], "verbose_name_plural": "Tipuri arc boltă"},
        ),
        migrations.AlterModelOptions(
            name="tipbateresindrila",
            options={"ordering": ["nume"], "verbose_name_plural": "Tipuri Batere Sindrila"},
        ),
        migrations.AlterModelOptions(
            name="tipboltapestealtar",
            options={"ordering": ["nume"], "verbose_name_plural": "Tipuri boltă peste altar"},
        ),
        migrations.AlterModelOptions(
            name="tipboltapronaos",
            options={"ordering": ["nume"], "verbose_name_plural": "Tipuri boltă pronaos/naos"},
        ),
        migrations.AlterModelOptions(
            name="tipbotsindrila",
            options={"ordering": ["nume"], "verbose_name_plural": "Tipuri Bot Sindrila"},
        ),
        migrations.AlterModelOptions(
            name="tipfundatie",
            options={"ordering": ["nume"], "verbose_name_plural": "Tipuri Fundatie"},
        ),
        migrations.AlterModelOptions(
            name="tipiconostas",
            options={"ordering": ["nume"], "verbose_name_plural": "Tipuri Iconostas"},
        ),
        migrations.AlterModelOptions(
            name="tipprelucraresindrila",
            options={"ordering": ["nume"], "verbose_name_plural": "Tipuri Prelucrare Sindrila"},
        ),
        migrations.AlterModelOptions(
            name="tipprinderesindrila",
            options={"ordering": ["nume"], "verbose_name_plural": "Tipuri Prindere Sindrila"},
        ),
        migrations.AlterModelOptions(
            name="tipsarpanta",
            options={"ordering": ["nume"], "verbose_name_plural": "Tipuri Sarpanta"},
        ),
        migrations.AlterModelOptions(
            name="tipstructuracatei",
            options={"ordering": ["nume"], "verbose_name_plural": "Tipuri Structură Căței"},
        ),
        migrations.AlterModelOptions(
            name="tipstructuracheotoare",
            options={"ordering": ["nume"], "verbose_name_plural": "Tipuri Structură Cheotoare"},
        ),
        migrations.AlterModelOptions(
            name="tiptiranti",
            options={"ordering": ["nume"], "verbose_name_plural": "Tip tiranti"},
        ),
        migrations.AlterModelOptions(
            name="tipturn",
            options={"ordering": ["nume"], "verbose_name_plural": "Tipuri Turn"},
        ),
        migrations.AlterModelOptions(
            name="tipusiiconostas",
            options={"ordering": ["nume"], "verbose_name_plural": "Tipuri Uși Iconostas"},
        ),
        migrations.AlterModelOptions(
            name="topografiebiserica",
            options={"ordering": ["nume"], "verbose_name_plural": "Topografii Biserică"},
        ),
        migrations.AlterModelOptions(
            name="utilizarebiserica",
            options={"ordering": ["nume"], "verbose_name_plural": "Utilizări Biserică"},
        ),
        migrations.AlterModelOptions(
            name="zugravbiserica",
            options={"verbose_name_plural": "Zugravi"},
        ),
    ]
