# Generated by Django 3.1.13 on 2021-10-25 21:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biserici", "0052_auto_20210916_2325"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0077_auto_20211026_0032"),
        ("nomenclatoare", "0018_historicaltipsistemstructural_tipsistemstructural"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalProprietateBiserica",
            new_name="HistoricalRegimProprietate",
        ),
        migrations.RenameModel(
            old_name="ProprietateBiserica",
            new_name="RegimProprietate",
        ),
        migrations.AlterModelOptions(
            name="cultbiserica",
            options={"ordering": ["nume"], "verbose_name_plural": "Culte biserică"},
        ),
        migrations.AlterModelOptions(
            name="historicalregimproprietate",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical regim proprietate",
            },
        ),
        migrations.AlterModelOptions(
            name="hram",
            options={"ordering": ["nume"], "verbose_name_plural": "Hram Biserică"},
        ),
        migrations.AlterModelOptions(
            name="regimproprietate",
            options={"ordering": ["nume"], "verbose_name_plural": "Regimul de proprietate"},
        ),
    ]
