# Generated by Django 3.1.13 on 2021-10-25 22:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0087_auto_20211026_0131'),
        ('biserici', '0052_auto_20210916_2325'),
        ('nomenclatoare', '0027_historicalmaterialmasaaltar_materialmasaaltar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElementInteriorBiserică',
            new_name='ElementInteriorBiserica',
        ),
        migrations.RenameModel(
            old_name='HistoricalElementInteriorBiserică',
            new_name='HistoricalElementInteriorBiserica',
        ),
        migrations.AlterModelOptions(
            name='elementinteriorbiserica',
            options={'ordering': ['nume'], 'verbose_name_plural': 'Elemente interior Biserica'},
        ),
        migrations.AlterModelOptions(
            name='historicalelementinteriorbiserica',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical element interior biserica'},
        ),
    ]
