# Generated by Django 3.1.13 on 2022-07-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatoare', '0029_elementbiserica_historicalelementbiserica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalamplasamentbiserica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical amplasament biserica', 'verbose_name_plural': 'historical Amplasamente Biserică'},
        ),
        migrations.AlterModelOptions(
            name='historicalamplasareturn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical amplasare turn', 'verbose_name_plural': 'historical Amplasări Turn'},
        ),
        migrations.AlterModelOptions(
            name='historicalasezaretalpaturn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical asezare talpa turn', 'verbose_name_plural': 'historical Așezări talpă turn'},
        ),
        migrations.AlterModelOptions(
            name='historicalboltapestealtar',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical bolta peste altar', 'verbose_name_plural': 'historical Boltă peste altar'},
        ),
        migrations.AlterModelOptions(
            name='historicalcomuna',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical comuna', 'verbose_name_plural': 'historical Comune'},
        ),
        migrations.AlterModelOptions(
            name='historicalctitorbiserica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ctitor biserica', 'verbose_name_plural': 'historical Ctitori'},
        ),
        migrations.AlterModelOptions(
            name='historicalcultbiserica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical cult biserica', 'verbose_name_plural': 'historical Culte biserică'},
        ),
        migrations.AlterModelOptions(
            name='historicaldecorturn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical decor turn', 'verbose_name_plural': 'historical Decoruri Turn'},
        ),
        migrations.AlterModelOptions(
            name='historicaldetaliupodturn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical detaliu pod turn', 'verbose_name_plural': 'historical Detalii podul turnului'},
        ),
        migrations.AlterModelOptions(
            name='historicaldimensiuneturn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical dimensiune turn', 'verbose_name_plural': 'historical Dimensiuni Turn'},
        ),
        migrations.AlterModelOptions(
            name='historicalelementansambluconstruit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical element ansamblu construit', 'verbose_name_plural': 'historical Elemente Ansamblu Construit'},
        ),
        migrations.AlterModelOptions(
            name='historicalelementbiserica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical element biserica', 'verbose_name_plural': 'historical Elemente Biserica'},
        ),
        migrations.AlterModelOptions(
            name='historicalelementimportant',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical element important', 'verbose_name_plural': 'historical Elemente Importante'},
        ),
        migrations.AlterModelOptions(
            name='historicalelementinteriorbiserica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical element interior biserica', 'verbose_name_plural': 'historical Elemente interior Biserica'},
        ),
        migrations.AlterModelOptions(
            name='historicalesentalemnoasa',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical esenta lemnoasa', 'verbose_name_plural': 'historical Esenta Lemnoasa'},
        ),
        migrations.AlterModelOptions(
            name='historicaleveniment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical eveniment', 'verbose_name_plural': 'historical Evenimente'},
        ),
        migrations.AlterModelOptions(
            name='historicalevenimentbiserica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical eveniment biserica', 'verbose_name_plural': 'historical Evenimente Istorice'},
        ),
        migrations.AlterModelOptions(
            name='historicalfinisaj',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical finisaj', 'verbose_name_plural': 'historical Finisaje biserică'},
        ),
        migrations.AlterModelOptions(
            name='historicalfinisajexterior',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical finisaj exterior', 'verbose_name_plural': 'historical Finisaje Exterioare'},
        ),
        migrations.AlterModelOptions(
            name='historicalfinisajinvelitoare',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical finisaj invelitoare', 'verbose_name_plural': 'historical Finisaj Învelitore'},
        ),
        migrations.AlterModelOptions(
            name='historicalfunctiunebiserica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical functiune biserica', 'verbose_name_plural': 'historical Funcțiuni Biserică'},
        ),
        migrations.AlterModelOptions(
            name='historicalgalerieturn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical galerie turn', 'verbose_name_plural': 'historical Galerii Turn'},
        ),
        migrations.AlterModelOptions(
            name='historicalhram',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical hram', 'verbose_name_plural': 'historical Hram Biserică'},
        ),
        migrations.AlterModelOptions(
            name='historicaljudet',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical judet', 'verbose_name_plural': 'historical Județe'},
        ),
        migrations.AlterModelOptions(
            name='historicallocalitate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical localitate', 'verbose_name_plural': 'historical Localități'},
        ),
        migrations.AlterModelOptions(
            name='historicallocalizarepictura',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical localizare pictura', 'verbose_name_plural': 'historical Localizări Pictură'},
        ),
        migrations.AlterModelOptions(
            name='historicalmaterial',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical material', 'verbose_name_plural': 'historical Materiale'},
        ),
        migrations.AlterModelOptions(
            name='historicalmaterialbolta',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical material bolta', 'verbose_name_plural': 'historical Materiale Boltă'},
        ),
        migrations.AlterModelOptions(
            name='historicalmaterialcor',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical material cor', 'verbose_name_plural': 'historical Materiale Cor'},
        ),
        migrations.AlterModelOptions(
            name='historicalmaterialcruci',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical material cruci', 'verbose_name_plural': 'historical Materiale Cruci'},
        ),
        migrations.AlterModelOptions(
            name='historicalmaterialestructura',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical materiale structura', 'verbose_name_plural': 'historical Materiale Structura'},
        ),
        migrations.AlterModelOptions(
            name='historicalmaterialestructurabolta',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical materiale structura bolta', 'verbose_name_plural': 'historical Materiale Structură Boltă'},
        ),
        migrations.AlterModelOptions(
            name='historicalmaterialfinisajpardoseli',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical material finisaj pardoseli', 'verbose_name_plural': 'historical Material Finisaj Pardoseli'},
        ),
        migrations.AlterModelOptions(
            name='historicalmaterialfinisajperetiinteriori',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical material finisaj pereti interiori', 'verbose_name_plural': 'historical Material Finisaj Pereti Interiori'},
        ),
        migrations.AlterModelOptions(
            name='historicalmaterialiconostas',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical material iconostas', 'verbose_name_plural': 'historical Materiale Iconostas'},
        ),
        migrations.AlterModelOptions(
            name='historicalmaterialinvelitoareturle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical material invelitoare turle', 'verbose_name_plural': 'historical Material învelitoare turle'},
        ),
        migrations.AlterModelOptions(
            name='historicalmaterialmasaaltar',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical material masa altar', 'verbose_name_plural': 'historical Materiale masă altar'},
        ),
        migrations.AlterModelOptions(
            name='historicalmaterialmobilier',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical material mobilier', 'verbose_name_plural': 'historical Materiale mobilier'},
        ),
        migrations.AlterModelOptions(
            name='historicalmesterbiserica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical mester biserica', 'verbose_name_plural': 'historical Meșteri'},
        ),
        migrations.AlterModelOptions(
            name='historicalmobilier',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical mobilier', 'verbose_name_plural': 'historical Mobilier'},
        ),
        migrations.AlterModelOptions(
            name='historicalmutarebiserica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical mutare biserica', 'verbose_name_plural': 'historical Mutări Biserică'},
        ),
        migrations.AlterModelOptions(
            name='historicalobiectcult',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical obiect cult', 'verbose_name_plural': 'historical Obiecte de Cult'},
        ),
        migrations.AlterModelOptions(
            name='historicalpeisagisticasit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical peisagistica sit', 'verbose_name_plural': 'historical Peisagistica sitului'},
        ),
        migrations.AlterModelOptions(
            name='historicalpersoana',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical persoana', 'verbose_name_plural': 'historical Persoane'},
        ),
        migrations.AlterModelOptions(
            name='historicalpersonalitatebiserica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical personalitate biserica', 'verbose_name_plural': 'historical Personalități Biserică'},
        ),
        migrations.AlterModelOptions(
            name='historicalplanimetrie',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical planimetrie', 'verbose_name_plural': 'historical Planimetrii'},
        ),
        migrations.AlterModelOptions(
            name='historicalplanturn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical plan turn', 'verbose_name_plural': 'historical Planuri Turn'},
        ),
        migrations.AlterModelOptions(
            name='historicalpozitionareturle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical pozitionare turle', 'verbose_name_plural': 'historical Poziționare turle'},
        ),
        migrations.AlterModelOptions(
            name='historicalregimproprietate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical regim proprietate', 'verbose_name_plural': 'historical Regimul de proprietate'},
        ),
        migrations.AlterModelOptions(
            name='historicalregistruiconostas',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical registru iconostas', 'verbose_name_plural': 'historical Registre Iconostas'},
        ),
        migrations.AlterModelOptions(
            name='historicalrelatiecimitir',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical relatie cimitir', 'verbose_name_plural': 'historical Relația cu cimitirul'},
        ),
        migrations.AlterModelOptions(
            name='historicalrelatietalpaturn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical relatie talpa turn', 'verbose_name_plural': 'historical Relații talpă turn'},
        ),
        migrations.AlterModelOptions(
            name='historicalsecol',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical secol', 'verbose_name_plural': 'historical Secole'},
        ),
        migrations.AlterModelOptions(
            name='historicalsingularitatebiserica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical singularitate biserica', 'verbose_name_plural': 'historical Singularități Biserică'},
        ),
        migrations.AlterModelOptions(
            name='historicalstatutbiserica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical statut biserica', 'verbose_name_plural': 'historical Statuturi Biserică'},
        ),
        migrations.AlterModelOptions(
            name='historicalstilturle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical stil turle', 'verbose_name_plural': 'historical Stilul turlelor'},
        ),
        migrations.AlterModelOptions(
            name='historicalstudiu',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical studiu', 'verbose_name_plural': 'historical Studii'},
        ),
        migrations.AlterModelOptions(
            name='historicalstudiudendocronologic',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical studiu dendocronologic', 'verbose_name_plural': 'historical Studii dendocronologice'},
        ),
        migrations.AlterModelOptions(
            name='historicalstudiuistoric',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical studiu istoric', 'verbose_name_plural': 'historical tudii Istorice'},
        ),
        migrations.AlterModelOptions(
            name='historicalsuportpictura',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical suport pictura', 'verbose_name_plural': 'historical Suport Pictură'},
        ),
        migrations.AlterModelOptions(
            name='historicalsursadatare',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sursa datare', 'verbose_name_plural': 'historical Surse Datări'},
        ),
        migrations.AlterModelOptions(
            name='historicaltehnicaiconostas',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tehnica iconostas', 'verbose_name_plural': 'historical Tehnici Iconostas'},
        ),
        migrations.AlterModelOptions(
            name='historicaltehnicapictura',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tehnica pictura', 'verbose_name_plural': 'historical Tehnici Pictura'},
        ),
        migrations.AlterModelOptions(
            name='historicaltiparcbolta',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tip arc bolta', 'verbose_name_plural': 'historical Tipuri arc boltă'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipbateresindrila',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tip batere sindrila', 'verbose_name_plural': 'historical Tipuri Batere Sindrila'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipboltapestealtar',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tip bolta peste altar', 'verbose_name_plural': 'historical Tipuri boltă peste altar'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipboltapronaos',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tip bolta pronaos', 'verbose_name_plural': 'historical Tipuri boltă pronaos/naos'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipbotsindrila',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tip bot sindrila', 'verbose_name_plural': 'historical Tipuri Bot Sindrila'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipfundatie',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tip fundatie', 'verbose_name_plural': 'historical Tipuri Fundatie'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipiconostas',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tip iconostas', 'verbose_name_plural': 'historical Tipuri Iconostas'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipprelucraresindrila',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tip prelucrare sindrila', 'verbose_name_plural': 'historical Tipuri Prelucrare Sindrila'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipprinderesindrila',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tip prindere sindrila', 'verbose_name_plural': 'historical Tipuri montaj șindrilă'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipsarpanta',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tip sarpanta', 'verbose_name_plural': 'historical Tipuri Sarpanta'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipsistemstructural',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tip sistem structural', 'verbose_name_plural': 'historical Tipuri sisteme structurale'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipstructuracatei',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tip structura catei', 'verbose_name_plural': 'historical Tipuri Structură Căței'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipstructuracheotoare',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tip structura cheotoare', 'verbose_name_plural': 'historical Tipuri Structură Cheotoare'},
        ),
        migrations.AlterModelOptions(
            name='historicaltiptiranti',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tip tiranti', 'verbose_name_plural': 'historical Tip tiranti'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipturn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tip turn', 'verbose_name_plural': 'historical Tipuri Turn'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipusiiconostas',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tip usi iconostas', 'verbose_name_plural': 'historical Tipuri Uși Iconostas'},
        ),
        migrations.AlterModelOptions(
            name='historicaltopografiebiserica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical topografie biserica', 'verbose_name_plural': 'historical Topografii Biserică'},
        ),
        migrations.AlterModelOptions(
            name='historicalutilizarebiserica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical utilizare biserica', 'verbose_name_plural': 'historical Utilizări Biserică'},
        ),
        migrations.AlterModelOptions(
            name='historicalzugravbiserica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical zugrav biserica', 'verbose_name_plural': 'historical Zugravi'},
        ),
        migrations.AlterField(
            model_name='historicalamplasamentbiserica',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalamplasareturn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalasezaretalpaturn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalboltapestealtar',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcomuna',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalctitorbiserica',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcultbiserica',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldecorturn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldetaliupodturn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldimensiuneturn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalelementansambluconstruit',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalelementbiserica',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalelementimportant',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalelementinteriorbiserica',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalesentalemnoasa',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaleveniment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalevenimentbiserica',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfinisaj',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfinisajexterior',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfinisajinvelitoare',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfunctiunebiserica',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalgalerieturn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalhram',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaljudet',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallocalitate',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallocalizarepictura',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterialbolta',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterialcor',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterialcruci',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterialestructura',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterialestructurabolta',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterialfinisajpardoseli',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterialfinisajperetiinteriori',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterialiconostas',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterialinvelitoareturle',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterialmasaaltar',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterialmobilier',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmesterbiserica',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmobilier',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmutarebiserica',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalobiectcult',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpeisagisticasit',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpersoana',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpersonalitatebiserica',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalplanimetrie',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalplanturn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpozitionareturle',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalregimproprietate',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalregistruiconostas',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalrelatiecimitir',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalrelatietalpaturn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsecol',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsingularitatebiserica',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalstatutbiserica',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalstilturle',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalstudiu',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalstudiudendocronologic',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalstudiuistoric',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsuportpictura',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsursadatare',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltehnicaiconostas',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltehnicapictura',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltiparcbolta',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltipbateresindrila',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltipboltapestealtar',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltipboltapronaos',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltipbotsindrila',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltipfundatie',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltipiconostas',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltipprelucraresindrila',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltipprinderesindrila',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltipsarpanta',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltipsistemstructural',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltipstructuracatei',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltipstructuracheotoare',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltiptiranti',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltipturn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltipusiiconostas',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltopografiebiserica',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalutilizarebiserica',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalzugravbiserica',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
