# Generated by Django 3.1.13 on 2021-09-16 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("app", "0005_auto_20210917_0125"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentaArtisticaPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Componenta Artistică",
                "verbose_name_plural": "Componenta Artistică",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ConservarePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conservare",
                "verbose_name_plural": "Conservare",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="DescrierePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descriere",
                "verbose_name_plural": "Descriere",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="FinisajPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finisaj",
                "verbose_name_plural": "Finisaj",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="IstoricPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Istoric",
                "verbose_name_plural": "Istoric",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PatrimoniuPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patrimoniu",
                "verbose_name_plural": "Patrimoniu",
            },
            bases=("wagtailcore.page",),
        ),
    ]
