# Generated by Django 3.1.13 on 2021-09-16 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_bisericapage_judet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identificarepage',
            name='judet',
        ),
    ]
