# Generated by Django 3.1.13 on 2021-09-16 23:13

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("nomenclatoare", "0010_historicaltiparcbolta_tiparcbolta"),
        ("app", "0008_remove_identificarepage_judet"),
    ]

    operations = [
        migrations.AddField(
            model_name="descrierepage",
            name="amplasament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.amplasamentbiserica",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="bolta_peste_altar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_biserici_bolta_peste_altar",
                to="nomenclatoare.boltapestealtar",
                verbose_name="Boltă peste altar",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="bolta_peste_altar_material",
            field=models.ManyToManyField(
                blank=True, related_name="p_biserici_bolta_peste_altar", to="nomenclatoare.Material"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="bolta_peste_altar_observatii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="bolta_peste_altar_tip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_biserici",
                to="nomenclatoare.tipboltapestealtar",
                verbose_name="Tip bolta peste altar",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="bolta_peste_altar_tipul_de_arc",
            field=models.ManyToManyField(
                blank=True, related_name="p_biserici_bolta_peste_altar", to="nomenclatoare.TipArcBolta"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="bolta_peste_naos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_biserici_bolta_peste_naos",
                to="nomenclatoare.tipboltapronaos",
                verbose_name="Boltă peste naos",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="bolta_peste_naos_material",
            field=models.ManyToManyField(
                blank=True, related_name="p_biserici_bolta_peste_naos", to="nomenclatoare.Material"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="bolta_peste_naos_observatii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="bolta_peste_naos_tipul_de_arc",
            field=models.ManyToManyField(
                blank=True, related_name="p_biserici_bolta_peste_naos", to="nomenclatoare.TipArcBolta"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="bolta_peste_pronaos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_biserici_bolta_peste_pronaos",
                to="nomenclatoare.tipboltapronaos",
                verbose_name="Boltă peste pronaos",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="bolta_peste_pronaos_material",
            field=models.ManyToManyField(
                blank=True, related_name="p_biserici_bolta_peste_pronaos", to="nomenclatoare.Material"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="bolta_peste_pronaos_observatii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="bolta_peste_pronaos_tipul_de_arc",
            field=models.ManyToManyField(
                blank=True, related_name="p_biserici_bolta_peste_pronaos", to="nomenclatoare.TipArcBolta"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="clopote_an",
            field=models.IntegerField(blank=True, null=True, verbose_name="Clopote (an)"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="clopote_inscriptie",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Clopote (Inscripție)"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="cor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="cor_material",
            field=models.ManyToManyField(blank=True, related_name="p_biserici_cor", to="nomenclatoare.Material"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="cor_observatii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="detalii_elemente",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="detalii_elemente_importante",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="detalii_materiale",
            field=wagtail.core.fields.RichTextField(
                blank=True, help_text="Materialele care compun structura de rezistentă a bisericii", null=True
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="elemente",
            field=models.ManyToManyField(
                blank=True, help_text="Elemente ansamblu construit", to="nomenclatoare.ElementBiserica"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="elemente_importante",
            field=models.ManyToManyField(
                blank=True, help_text="Elemente ansamblu construit", to="nomenclatoare.ElementImportant"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="fundatia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_biserici",
                to="nomenclatoare.tipfundatie",
                verbose_name="Fundația",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="gabarit_exterior_al_talpilor",
            field=models.ImageField(
                blank=True,
                help_text="o schiță a planului tălpilor / elevației /  turnului / triunghiului șarpantei",
                null=True,
                upload_to="schite",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="masa_altar_material_blat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_masa_altar_blat",
                to="nomenclatoare.material",
                verbose_name="Sfânta masă a altarului (materialul blatului)",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="masa_altar_material_picior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_masa_altar_picior",
                to="nomenclatoare.material",
                verbose_name="Sfânta masă a altarului (materialul piciorului)",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="masa_altar_observatii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="materiale",
            field=models.ManyToManyField(
                blank=True, help_text="Materiale folosite in construcția bisericii", to="nomenclatoare.Material"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_accese_altar",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr accese altar"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_accese_altar_detalii",
            field=wagtail.core.fields.RichTextField(
                blank=True, null=True, verbose_name="Număr accese altar (observații)"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_accese_naos",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr accese naos"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_accese_naos_detalii",
            field=wagtail.core.fields.RichTextField(
                blank=True, null=True, verbose_name="Număr accese naos (observații)"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_accese_pridvor",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr accese pridvor"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_accese_pridvor_detalii",
            field=wagtail.core.fields.RichTextField(
                blank=True, null=True, verbose_name="Număr accese pridvor (observații)"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_accese_pronaos",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr accese pronaos"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_accese_pronaos_detalii",
            field=wagtail.core.fields.RichTextField(
                blank=True, null=True, verbose_name="Număr accese pronaos (observații)"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_geamuri_altar",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr geamuri altar"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_geamuri_altar_detalii",
            field=wagtail.core.fields.RichTextField(
                blank=True, null=True, verbose_name="Număr geamuri altar (observații)"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_geamuri_naos",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr geamuri naos"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_geamuri_naos_detalii",
            field=wagtail.core.fields.RichTextField(
                blank=True, null=True, verbose_name="Număr geamuri naos (observații)"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_geamuri_pridvor",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr geamuri pridvor"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_geamuri_pridvor_detalii",
            field=wagtail.core.fields.RichTextField(
                blank=True, null=True, verbose_name="Număr geamuri pridvor (observații)"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_geamuri_pronaos",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr geamuri pronaos"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_geamuri_pronaos_detalii",
            field=wagtail.core.fields.RichTextField(
                blank=True, null=True, verbose_name="Număr geamuri pronaos (observații)"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="oachiesi_aerisitoare",
            field=models.BooleanField(default=False, verbose_name="Ochieși / Aerisitoare "),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="oachiesi_aerisitoare_detalii",
            field=wagtail.core.fields.RichTextField(
                blank=True, null=True, verbose_name="Ochieși / Aerisitoare (observații)"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="observatii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="peisagistica_sitului",
            field=models.ManyToManyField(blank=True, to="nomenclatoare.PeisagisticaSit"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="planimetria_bisericii",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nomenclatoare.planimetrie"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="relatia_cu_cimitirul",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nomenclatoare.relatiecimitir"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="sarpanta_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Șarpantă (observații)"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="sarpanta_material_cruci",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_material_cruci",
                to="nomenclatoare.material",
                verbose_name="Șarpantă (material cruci)",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="sarpanta_numar_cruci",
            field=models.IntegerField(blank=True, null=True, verbose_name="Șarpantă (număr cruci)"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="sarpanta_numar_turnulete",
            field=models.IntegerField(blank=True, null=True, verbose_name="Șarpantă (număr turnulețe decorative)"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="sarpanta_tip",
            field=models.ManyToManyField(blank=True, to="nomenclatoare.TipSarpanta", verbose_name="Șarpantă (tip)"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="sarpanta_veche_nefolosita",
            field=models.BooleanField(default=False, verbose_name="Șarpantă veche nefolosită sub șarpanta actuală"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="sistem_in_catei",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_biserici",
                to="nomenclatoare.tipstructuracatei",
                verbose_name="Sistem structural al corpului bisericii În căței",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="sistem_in_cheotoare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_biserici",
                to="nomenclatoare.tipstructuracheotoare",
                verbose_name="Sistem structural al corpului bisericii În cheotoare",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="sistem_mixt",
            field=wagtail.core.fields.RichTextField(
                blank=True, null=True, verbose_name="Sistem structural al corpului bisericii mixt"
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="solee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="solee_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Solee (observații)"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="topografie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.topografiebiserica",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="toponim",
            field=models.CharField(blank=True, help_text="denumirea locului", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="toponim_sursa",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Sursă informații"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="turn_amplasare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.amplasareturn",
                verbose_name="Turn (amplasare)",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="turn_asezare_talpi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.asezaretalpaturn",
                verbose_name="Turn (așezarea tălpilor turnului în legătură cu butea bisericii)",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="turn_decor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.decorturn",
                verbose_name="Turn (decor)",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="turn_dimensiune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.dimensiuneturn",
                verbose_name="Turn (dimensiune)",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="turn_galerie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.galerieturn",
                verbose_name="Turn (galerie)",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="turn_numar",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr de turnuri"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="turn_numar_arcade",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr arcade Turn deschis"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="turn_numar_arcade_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Detalii arcade Turn deschis"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="turn_numar_talpi",
            field=models.IntegerField(blank=True, null=True, verbose_name="Turn (număr de tălpi)"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="turn_observatii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="turn_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.planturn",
                verbose_name="Turn (plan)",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="turn_relatie_talpi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.relatietalpaturn",
                verbose_name="Turn (relația dintre tălpile turnului)",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="turn_tip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.tipturn",
                verbose_name="Turn (tip)",
            ),
        ),
    ]
