# Generated by Django 3.1.13 on 2021-09-21 13:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatoare', '0010_historicaltiparcbolta_tiparcbolta'),
        ('app', '0009_auto_20210917_0213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descrierepage',
            options={'verbose_name': 'Capitol Descriere', 'verbose_name_plural': 'Capitole Descriere'},
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='singularitate_detalii',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații'),
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='utilizare_detalii',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații'),
        ),
        migrations.CreateModel(
            name='ElementeImportanteAnsambluConstruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.elementimportant')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='elemente_importante_ansamblu_construit', to='app.descrierepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElementeAnsambluConstruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.elementansambluconstruit')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='elemente_ansamblu_construit', to='app.descrierepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
