# Generated by Django 3.1.13 on 2021-09-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_auto_20210921_1644"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="descrierepage",
            name="gabarit_exterior_al_talpilor",
        ),
    ]
