# Generated by Django 3.1.13 on 2021-09-21 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("app", "0011_remove_descrierepage_gabarit_exterior_al_talpilor"),
    ]

    operations = [
        migrations.AddField(
            model_name="descrierepage",
            name="gabarit_exterior_al_talpilor",
            field=models.ForeignKey(
                blank=True,
                help_text="o schiță a planului tălpilor / elevației /  turnului / triunghiului șarpantei",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
