# Generated by Django 3.1.13 on 2021-09-21 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatoare', '0010_historicaltiparcbolta_tiparcbolta'),
        ('app', '0012_descrierepage_gabarit_exterior_al_talpilor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descrierepage',
            name='turn_amplasare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.amplasareturn', verbose_name='Amplasare'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='turn_asezare_talpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.asezaretalpaturn', verbose_name='Așezarea tălpilor turnului în legătură cu butea bisericii'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='turn_decor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.decorturn', verbose_name='Decor'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='turn_dimensiune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.dimensiuneturn', verbose_name='Dimensiune'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='turn_galerie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.galerieturn', verbose_name='Galerie'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='turn_numar_talpi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Număr de tălpi'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='turn_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.planturn', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='turn_relatie_talpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.relatietalpaturn', verbose_name='Relația dintre tălpile turnului'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='turn_tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tipturn', verbose_name='Tip'),
        ),
    ]
