# Generated by Django 3.1.13 on 2021-09-21 21:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("nomenclatoare", "0010_historicaltiparcbolta_tiparcbolta"),
        ("app", "0013_auto_20210921_1842"),
    ]

    operations = [
        migrations.AddField(
            model_name="conservarepage",
            name="alte_elemente_importante",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="alte_elemente_importante_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="bolti",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="bolti_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="bolti_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="corp_biserica",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="corp_biserica_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="corp_biserica_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="cosoroabe",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="cosoroabe_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="cosoroabe_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="elemente_arhitecturale",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="elemente_arhitecturale_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="finisaj_exterior",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="finisaj_exterior_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="finisaj_exterior_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="finisaj_pereti_interiori",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="finisaj_pereti_interiori_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="finisaj_pereti_interiori_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="finisaj_tavane_si_bolti",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="finisaj_tavane_si_bolti_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="finisaj_tavane_si_bolti_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="fundatii",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="fundatii_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="fundatii_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="instalatie_electrica",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="instalatie_electrica_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="instalatie_electrica_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="instalatie_termica",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="instalatie_termica_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="instalatie_termica_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="invelitoare_sarpanta_si_turn",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="invelitoare_sarpanta_si_turn_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="invelitoare_sarpanta_si_turn_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="mobilier",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="mobilier_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="mobilier_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="obiecte_de_cult",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="obiecte_de_cult_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="obiecte_de_cult_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="paratraznet",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="paratraznet_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="paratraznet_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="pardoseli_interioare",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="pardoseli_interioare_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="pardoseli_interioare_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="sarpanta_peste_corp_biserica",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="sarpanta_peste_corp_biserica_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="sarpanta_peste_corp_biserica_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="sarpanta_turn",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="sarpanta_turn_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="sarpanta_turn_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="sit",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="sit_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="strat_pictural",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="strat_pictural_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="strat_pictural_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="structura_turn",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="structura_turn_detalii",
            field=wagtail.core.fields.RichTextField(
                blank=True,
                help_text="tarea structurii turnului, inclusiv a tălpilor și a coifului",
                null=True,
                verbose_name="Observații",
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="structura_turn_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="talpi",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="talpi_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="talpi_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="teren",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="teren_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="teren_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="vegetatie",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="vegetatie_detalii",
            field=wagtail.core.fields.RichTextField(
                blank=True,
                help_text="Vegetație invazivă ce poate pune monumentul în pericol",
                null=True,
                verbose_name="Observații",
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="vegetatie_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="zona_din_jurul_biserici",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Stare"
            ),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="zona_din_jurul_biserici_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="zona_din_jurul_biserici_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="bolta_peste_altar_material",
            field=models.ManyToManyField(
                blank=True,
                related_name="p_biserici_bolta_peste_altar",
                to="nomenclatoare.Material",
                verbose_name="Material",
            ),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="bolta_peste_altar_observatii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="bolta_peste_altar_tip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_biserici",
                to="nomenclatoare.tipboltapestealtar",
                verbose_name="Tip",
            ),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="bolta_peste_altar_tipul_de_arc",
            field=models.ManyToManyField(
                blank=True,
                related_name="p_biserici_bolta_peste_altar",
                to="nomenclatoare.TipArcBolta",
                verbose_name="Tipul de arc",
            ),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="bolta_peste_naos_observatii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="bolta_peste_pronaos_observatii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="clopote_an",
            field=models.IntegerField(blank=True, null=True, verbose_name="An"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="clopote_inscriptie",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Inscripție"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="cor_observatii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="masa_altar_material_blat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_masa_altar_blat",
                to="nomenclatoare.material",
                verbose_name="Materialul blatului",
            ),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="masa_altar_material_picior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_masa_altar_picior",
                to="nomenclatoare.material",
                verbose_name="Materialul piciorului",
            ),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="masa_altar_observatii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="numar_accese_altar_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații Altar"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="numar_accese_naos_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații Naos"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="numar_accese_pridvor_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații Pridvor"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="numar_accese_pronaos_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații Pronaos"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="numar_geamuri_altar_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații Altar"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="numar_geamuri_naos_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații Naos"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="numar_geamuri_pridvor_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații Pridvor"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="numar_geamuri_pronaos_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații Pronaos"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="oachiesi_aerisitoare_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="sarpanta_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="sarpanta_material_cruci",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_material_cruci",
                to="nomenclatoare.material",
                verbose_name="Material cruci",
            ),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="sarpanta_numar_cruci",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr cruci"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="sarpanta_numar_turnulete",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr turnulețe decorative"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="sarpanta_tip",
            field=models.ManyToManyField(blank=True, to="nomenclatoare.TipSarpanta", verbose_name="Tip"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="sarpanta_veche_nefolosita",
            field=models.BooleanField(default=False, verbose_name="Veche nefolosită sub șarpanta actuală"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="solee_detalii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="turn_asezare_talpi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.asezaretalpaturn",
                verbose_name="Așezarea tălpilor turnului în legătură cu corpul bisericii",
            ),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="turn_observatii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
    ]
