# Generated by Django 3.1.13 on 2021-09-24 11:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("nomenclatoare", "0010_historicaltiparcbolta_tiparcbolta"),
        ("app", "0024_auto_20210924_1416"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ctitori",
            old_name="detalii",
            new_name="observatii",
        ),
        migrations.RenameField(
            model_name="evenimente",
            old_name="detalii",
            new_name="observatii",
        ),
        migrations.RenameField(
            model_name="mesteri",
            old_name="detalii",
            new_name="observatii",
        ),
        migrations.RenameField(
            model_name="mutaribiserica",
            old_name="detalii",
            new_name="observatii",
        ),
        migrations.RenameField(
            model_name="personalitati",
            old_name="detalii",
            new_name="observatii",
        ),
        migrations.RenameField(
            model_name="povestibiserica",
            old_name="detalii",
            new_name="observatii",
        ),
        migrations.RenameField(
            model_name="zugravi",
            old_name="detalii",
            new_name="observatii",
        ),
        migrations.RemoveField(
            model_name="evenimente",
            name="sursa",
        ),
        migrations.RemoveField(
            model_name="mutaribiserica",
            name="nume",
        ),
        migrations.AddField(
            model_name="mutaribiserica",
            name="adresa",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="mutaribiserica",
            name="latitudine",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mutaribiserica",
            name="localitate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_biserici_mutari",
                to="nomenclatoare.localitate",
            ),
        ),
        migrations.AddField(
            model_name="mutaribiserica",
            name="longitudine",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ctitori",
            name="sursa",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Sursa"),
        ),
        migrations.AlterField(
            model_name="mesteri",
            name="sursa",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Sursa"),
        ),
        migrations.AlterField(
            model_name="mutaribiserica",
            name="sursa",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Sursa"),
        ),
        migrations.AlterField(
            model_name="personalitati",
            name="sursa",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Sursa"),
        ),
        migrations.AlterField(
            model_name="povestibiserica",
            name="sursa",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Sursa"),
        ),
        migrations.AlterField(
            model_name="zugravi",
            name="sursa",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Sursa"),
        ),
    ]
