# Generated by Django 3.1.13 on 2021-09-24 13:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatoare', '0013_historicalmaterialinvelitoareturle_materialinvelitoareturle'),
        ('app', '0029_auto_20210924_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='descrierepage',
            name='finisaj_exterior_observatii',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='finisaj_exterior_tip',
            field=models.ManyToManyField(blank=True, to='nomenclatoare.FinisajExterior', verbose_name='Tip'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inchidere_tambur', to='nomenclatoare.finisajexterior', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_observatii',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrila_cu_horj',
            field=models.BooleanField(default=False, verbose_name='Șindrila cu horj'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrila_cu_tesitura',
            field=models.BooleanField(default=False, verbose_name='Șindrila cu teșitură'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrila_grosime_medie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (grosime medie)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrila_latime_medie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (lățime medie)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrila_lungime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (lungime)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrila_numar_straturi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (număr straturi)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrila_pasul_baterii',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (pasul baterii)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrila_pasul_latuirii',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (pasul lățuirii)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrlia_esenta_lemnoasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inchidere_tambur_turn_sindrlia_esenta', to='nomenclatoare.esentalemnoasa', verbose_name='Șindrila (esență lemnoasă)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrlia_forma_botului',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inchidere_tambur_turn', to='nomenclatoare.tipbotsindrila', verbose_name='Șindrila (forma botului)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrlia_prelucrare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inchidere_tambur_turn', to='nomenclatoare.tipprelucraresindrila', verbose_name='Șindrila (prelucrare)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrlia_tipul_de_batere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inchidere_tambur_turn', to='nomenclatoare.tipbateresindrila', verbose_name='Șindrila (tipul de batere)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrlia_tipul_prindere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inchidere_tambur_turn', to='nomenclatoare.tipprinderesindrila', verbose_name='Șindrila (tipul de prindere)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_corp_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_corp', to='nomenclatoare.finisajexterior', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_corp_observatii',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrila_cu_horj',
            field=models.BooleanField(default=False, verbose_name='Șindrila cu horj'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrila_cu_tesitura',
            field=models.BooleanField(default=False, verbose_name='Șindrila cu teșitură'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrila_grosime_medie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (grosime medie)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrila_latime_medie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (lățime medie)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrila_lungime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (lungime)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrila_numar_straturi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (număr straturi)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrila_pasul_baterii',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (pasul baterii)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrila_pasul_latuirii',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (pasul lățuirii)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrlia_esenta_lemnoasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_corp_sindrlia_esenta', to='nomenclatoare.esentalemnoasa', verbose_name='Șindrila (esență lemnoasă)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrlia_forma_botului',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_corp', to='nomenclatoare.tipbotsindrila', verbose_name='Șindrila (forma botului)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrlia_prelucrare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_corp', to='nomenclatoare.tipprelucraresindrila', verbose_name='Șindrila (prelucrare)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrlia_tipul_de_batere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_corp', to='nomenclatoare.tipbateresindrila', verbose_name='Șindrila (tipul de batere)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrlia_tipul_prindere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_corp', to='nomenclatoare.tipprinderesindrila', verbose_name='Șindrila (tipul de prindere)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turle_material',
            field=models.ManyToManyField(blank=True, to='nomenclatoare.MaterialInvelitoareTurle', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turle_observatii',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrila_cu_horj',
            field=models.BooleanField(default=False, verbose_name='Șindrila cu horj'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrila_cu_tesitura',
            field=models.BooleanField(default=False, verbose_name='Șindrila cu teșitură'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrila_grosime_medie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (grosime medie)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrila_latime_medie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (lățime medie)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrila_lungime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (lungime)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrila_numar_straturi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (număr straturi)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrila_pasul_baterii',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (pasul baterii)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrila_pasul_latuirii',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (pasul lățuirii)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrlia_esenta_lemnoasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turle_sindrlia_esenta', to='nomenclatoare.esentalemnoasa', verbose_name='Șindrila (esență lemnoasă)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrlia_forma_botului',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turle', to='nomenclatoare.tipbotsindrila', verbose_name='Șindrila (forma botului)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrlia_prelucrare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turle', to='nomenclatoare.tipprelucraresindrila', verbose_name='Șindrila (prelucrare)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrlia_tipul_de_batere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turle', to='nomenclatoare.tipbateresindrila', verbose_name='Șindrila (tipul de batere)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrlia_tipul_prindere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turle', to='nomenclatoare.tipprinderesindrila', verbose_name='Șindrila (tipul de prindere)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turn_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turn', to='nomenclatoare.finisajexterior', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turn_observatii',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrila_cu_horj',
            field=models.BooleanField(default=False, verbose_name='Șindrila cu horj'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrila_cu_tesitura',
            field=models.BooleanField(default=False, verbose_name='Șindrila cu teșitură'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrila_grosime_medie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (grosime medie)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrila_latime_medie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (lățime medie)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrila_lungime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (lungime)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrila_numar_straturi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (număr straturi)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrila_pasul_baterii',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (pasul baterii)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrila_pasul_latuirii',
            field=models.IntegerField(blank=True, null=True, verbose_name='Șindrila (pasul lățuirii)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrlia_esenta_lemnoasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turn_sindrlia_esenta', to='nomenclatoare.esentalemnoasa', verbose_name='Șindrila (esență lemnoasă)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrlia_forma_botului',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turn', to='nomenclatoare.tipbotsindrila', verbose_name='Șindrila (forma botului)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrlia_prelucrare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turn', to='nomenclatoare.tipprelucraresindrila', verbose_name='Șindrila (prelucrare)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrlia_tipul_de_batere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turn', to='nomenclatoare.tipbateresindrila', verbose_name='Șindrila (tipul de batere)'),
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrlia_tipul_prindere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turn', to='nomenclatoare.tipprinderesindrila', verbose_name='Șindrila (tipul de prindere)'),
        ),
        migrations.AlterField(
            model_name='ctitori',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='ctitori', to='app.istoricpage'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='fundatia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.tipfundatie', verbose_name='Tip'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='sistem_in_catei',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.tipstructuracatei', verbose_name='Tip'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='sistem_in_cheotoare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.tipstructuracheotoare', verbose_name='Tip'),
        ),
        migrations.AlterField(
            model_name='mesteri',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='mesteri', to='app.istoricpage'),
        ),
        migrations.AlterField(
            model_name='personalitati',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='personalitati', to='app.istoricpage'),
        ),
        migrations.AlterField(
            model_name='zugravi',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='zugravi', to='app.istoricpage'),
        ),
        migrations.CreateModel(
            name='FinisajePronaos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.elementbiserica')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.finisaj')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='finisaje_pronaos', to='app.descrierepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinisajePortic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.elementbiserica')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.finisaj')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='finisaje_portic', to='app.descrierepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinisajeNaos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.elementbiserica')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.finisaj')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='finisaje_naos', to='app.descrierepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinisajeAltar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.elementbiserica')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.finisaj')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='finisaje_altar', to='app.descrierepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
