# Generated by Django 3.1.13 on 2021-09-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_auto_20210924_1658"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="finisajealtar",
            options={},
        ),
    ]
