# Generated by Django 3.1.13 on 2021-09-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_auto_20210924_1700"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="finisajenaos",
            options={},
        ),
        migrations.AlterModelOptions(
            name="finisajeportic",
            options={},
        ),
        migrations.AlterModelOptions(
            name="finisajepronaos",
            options={},
        ),
    ]
