# Generated by Django 3.1.13 on 2021-09-24 14:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("nomenclatoare", "0013_historicalmaterialinvelitoareturle_materialinvelitoareturle"),
        ("app", "0038_pozegeneraleexterior_pozegeneraleinterior"),
    ]

    operations = [
        migrations.AddField(
            model_name="descrierepage",
            name="interventii_invelitoare_alte_tipuri_invelitoare",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Alte tipuri"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="interventii_invelitoare_etape_anterioare_vizibile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="interventii_invelitoare_observatii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="interventii_invelitoare_sindrila_cu_horj",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="interventii_invelitoare_sindrila_cu_tesitura",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="interventii_invelitoare_sindrila_numar_straturi",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="interventii_invelitoare_sindrila_pasul_latuirii",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="interventii_invelitoare_sindrlia_esenta_lemnoasa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interventii_invelitoare",
                to="nomenclatoare.esentalemnoasa",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="interventii_invelitoare_sindrlia_forma_botului",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interventii_invelitoare",
                to="nomenclatoare.tipbotsindrila",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="interventii_invelitoare_sindrlia_tipul_de_batere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interventii_invelitoare",
                to="nomenclatoare.tipbateresindrila",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="invelitoare_actuala_an",
            field=models.IntegerField(blank=True, null=True, verbose_name="An montaj"),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="invelitoare_actuala_observatii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
        migrations.CreateModel(
            name="EtapeIstoriceVizibile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("datat", models.BooleanField(default=False)),
                ("an", models.IntegerField(blank=True, null=True)),
                ("interventie_neconforma", models.BooleanField(default=False)),
                ("sursa", wagtail.core.fields.RichTextField(blank=True, null=True)),
                ("observatii", wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații")),
                (
                    "element",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nomenclatoare.elementbiserica",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etape_istorice_vizibile",
                        to="app.descrierepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
