# Generated by Django 3.1.13 on 2021-09-24 14:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('nomenclatoare', '0013_historicalmaterialinvelitoareturle_materialinvelitoareturle'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('app', '0039_auto_20210924_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisticEtapeIstoriceVizibile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('datat', models.BooleanField(default=False)),
                ('an', models.IntegerField(blank=True, null=True)),
                ('interventie_neconforma', models.BooleanField(default=False)),
                ('sursa', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.elementbiserica')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='etape_istorice_vizibile', to='app.componentaartisticapage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FinisajPage',
        ),
    ]
