# Generated by Django 3.1.13 on 2021-09-24 14:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatoare', '0013_historicalmaterialinvelitoareturle_materialinvelitoareturle'),
        ('app', '0040_auto_20210924_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentaartisticapage',
            name='altar_decor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_decoruri_altar', to='nomenclatoare.finisajiconostas', verbose_name='Decor'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='altar_observatii',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='altar_piciorul_mesei',
            field=models.ManyToManyField(blank=True, related_name='p_piciorul_mesei', to='nomenclatoare.Material', verbose_name='Piciorul mesei'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='altar_placa_mesei',
            field=models.ManyToManyField(blank=True, related_name='p_placa_mesei', to='nomenclatoare.Material', verbose_name='Placa mesei'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='alte_icoane_vechi',
            field=models.BooleanField(default=False, verbose_name='Alte icoane vechi'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='alte_icoane_vechi_observatii',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='elemente_observatii',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='elemente_sculptate',
            field=models.BooleanField(default=False, verbose_name='Elemente sculptate / decoruri în biserică'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='iconostas_naos_altar_materiale',
            field=models.ManyToManyField(blank=True, related_name='p_iconostasuri_naos_altar', to='nomenclatoare.Material', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='iconostas_naos_altar_numar_intrari',
            field=models.IntegerField(blank=True, null=True, verbose_name='Număr intrări'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='iconostas_naos_altar_observatii',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='iconostas_naos_altar_registre',
            field=models.ManyToManyField(blank=True, related_name='p_iconostasuri_naos_altar', to='nomenclatoare.RegistruIconostas', verbose_name='Registru'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='iconostas_naos_altar_tehnica',
            field=models.ManyToManyField(blank=True, related_name='p_iconostasuri_naos_altar', to='nomenclatoare.FinisajIconostas', verbose_name='Tehnică'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='iconostas_naos_altar_tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_iconostasuri_naos_altar', to='nomenclatoare.tipiconostas', verbose_name='Tip'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='iconostas_naos_altar_tip_usi',
            field=models.ManyToManyField(blank=True, related_name='p_iconostasuri_naos_altar', to='nomenclatoare.TipUsiIconostas', verbose_name='Tip uși'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='iconostas_pronaos_naos_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_iconostasuri_pronaos_naos', to='nomenclatoare.material', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='iconostas_pronaos_naos_numar_intrari',
            field=models.IntegerField(blank=True, null=True, verbose_name='Număr intrări'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='iconostas_pronaos_naos_observatii',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='iconostas_pronaos_naos_tehnica',
            field=models.ManyToManyField(blank=True, related_name='p_iconostasuri_pronaos_naos', to='nomenclatoare.FinisajIconostas', verbose_name='Tehnica'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='iconostas_pronaos_naos_tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_iconostasuri_pronaos_naos', to='nomenclatoare.tipiconostas', verbose_name='Tip'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='mobiliere',
            field=models.ManyToManyField(blank=True, to='nomenclatoare.Material', verbose_name='Mobilier'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='mobiliere_observatii',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='obiecte_de_cult',
            field=models.ManyToManyField(blank=True, to='nomenclatoare.ObiectCult', verbose_name='Obiecte de cult'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='obiecte_de_cult_observatii',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='obiecte_instrainate',
            field=models.BooleanField(default=False, verbose_name='Obiecte de cult înstrăinate'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='obiecte_instrainate_observatii',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='proscomidie',
            field=models.BooleanField(default=False, verbose_name='Proscomidie în exteriorul altarului'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='suport_proscomidie',
            field=models.ManyToManyField(blank=True, to='nomenclatoare.SuportPictura'),
        ),
    ]
