# Generated by Django 3.1.13 on 2021-09-24 15:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('nomenclatoare', '0013_historicalmaterialinvelitoareturle_materialinvelitoareturle'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('app', '0042_auto_20210924_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoarePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('vechime', models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C')], help_text='Printr-un algorim definit se va da automat o notă de la 1-5 în funcție de vechimea monumentului si a picturii descrise conform OMCC2682/2003 ETC', null=True, verbose_name='Clasa')),
                ('vechime_observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('integritate', models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C')], help_text='Integritate / Autenticitate', null=True, verbose_name='Clasa')),
                ('integritate_observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('unicitate', models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C')], help_text='Unicitate / raritate', null=True, verbose_name='Clasa')),
                ('unicitate_observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('valoare_memoriala', models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C')], help_text='evenimente, personalități', null=True, verbose_name='Clasa')),
                ('valoare_memoriala_observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('peisaj_cultural', models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C')], help_text='Parte definitorie a peisajului cultural al zonei', null=True, verbose_name='Clasa')),
                ('peisaj_cultural_observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('valoare_sit', models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C')], help_text='Valoarea sitului împreună cu toate componentele ansamblului din care face parte, ținând cont de integritate, autenticitate, estetică peisageră, biodiversitate, etc. SUBIECTIV', null=True, verbose_name='Clasa')),
                ('valoare_sit_observatii', models.TextField(blank=True, help_text='Descriere a elementelor valoroase, particulare', null=True, verbose_name='Observații')),
                ('estetica', models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C')], help_text='Estetică / Arhitectură', null=True, verbose_name='Clasa')),
                ('estetica_observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('mestesug', models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C')], help_text='Meșteșug (calitatea muncii -  a se vedea golurile dintre lemne (dintre bârne în general dar în special la așezarea elementelor orizontale peste cele verticale))', null=True, verbose_name='Clasa')),
                ('mestesug_observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('pictura', models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C')], null=True, verbose_name='Clasa')),
                ('pictura_observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('folosinta_actuala', models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C')], help_text='Folosință actuală / singura biserică din sat / loc al patrimoniului imaterial', null=True, verbose_name='Clasa')),
                ('folosinta_actuala_observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('relevanta_actuala', models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C')], help_text='Relevanța actuală pentru comunitatea locală (prin reprezentanții săi: preot, crâsnic, învățător, familii de bază)', null=True, verbose_name='Clasa')),
                ('relevanta_actuala_observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('potential', models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C')], help_text='Potențialul de beneficii aduse comunității locale', null=True, verbose_name='Clasa')),
                ('potential_observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
            ],
            options={
                'verbose_name': 'Valoare',
                'verbose_name_plural': 'Valoare',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_exterioara_anul_picturii',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anul picturii'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_exterioara_datare_prin_interval_timp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Datare prin interval de timp'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_exterioara_datare_secol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_localizari_exterioare', to='nomenclatoare.secol', verbose_name='Datare secol'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_exterioara_localizare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_localizari_exterioare', to='nomenclatoare.localizarepictura', verbose_name='Proporția de suprafață acoperită'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_exterioara_numar_straturi_pictura',
            field=models.IntegerField(blank=True, null=True, verbose_name='Număr straturi'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_exterioara_suport',
            field=models.ManyToManyField(blank=True, related_name='p_localizari_exterioare', to='nomenclatoare.SuportPictura', verbose_name='Suport'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_exterioara_sursa_datare',
            field=models.ManyToManyField(blank=True, related_name='p_componente_artistice_exterioare', to='nomenclatoare.SursaDatare', verbose_name='Sursa datare'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_exterioara_tehnica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_localizari_exterioare', to='nomenclatoare.tehnicapictura', verbose_name='Tehnică'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_interioara_anul_picturii',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anul picturii'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_interioara_datare_prin_interval_timp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Datare prin interval de timp'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_interioara_datare_secol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_localizari_interioare', to='nomenclatoare.secol', verbose_name='Datare secol'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_interioara_localizare_observatii',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observatii'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_interioara_numar_straturi_pictura',
            field=models.IntegerField(blank=True, null=True, verbose_name='Număr straturi'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_interioara_suport',
            field=models.ManyToManyField(blank=True, related_name='p_localizari_interioare', to='nomenclatoare.SuportPictura', verbose_name='Suport'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_interioara_sursa_datare',
            field=models.ManyToManyField(blank=True, related_name='p_componente_artistice_interioare', to='nomenclatoare.SursaDatare', verbose_name='Sursa datare'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_interioara_tehnica_pictura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tehnicapictura', verbose_name='Tehnică'),
        ),
        migrations.DeleteModel(
            name='PatrimoniuPage',
        ),
    ]
