# Generated by Django 3.1.13 on 2021-10-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20211005_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementeimportanteansambluconstruit',
            name='element_disonant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elementeimportanteansambluconstruit',
            name='element_important',
            field=models.BooleanField(default=False),
        ),
    ]
