# Generated by Django 3.1.13 on 2021-10-14 09:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_identificarepage_hram'),
    ]

    operations = [
        migrations.AddField(
            model_name='istoricpage',
            name='are_mutari',
            field=models.BooleanField(default=False, verbose_name='Pisanie'),
        ),
        migrations.AddField(
            model_name='istoricpage',
            name='are_pisanie',
            field=models.BooleanField(default=False, verbose_name='Pisanie'),
        ),
        migrations.AddField(
            model_name='istoricpage',
            name='are_studiu_dendro',
            field=models.BooleanField(default=False, verbose_name='Pisanie'),
        ),
        migrations.AddField(
            model_name='istoricpage',
            name='lista_ctitori',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=20),
        ),
        migrations.AddField(
            model_name='istoricpage',
            name='lista_mesteri',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=20),
        ),
        migrations.AddField(
            model_name='istoricpage',
            name='lista_personalitati',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=20),
        ),
        migrations.AddField(
            model_name='istoricpage',
            name='lista_zugravi',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=20),
        ),
    ]
