# Generated by Django 3.1.13 on 2021-10-14 10:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("nomenclatoare", "0017_historicalmaterialestructurabolta_materialestructurabolta"),
        ("app", "0063_auto_20211014_1222"),
    ]

    operations = [
        migrations.AddField(
            model_name="descrierepage",
            name="ansamblu_construit",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=20
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="are_model_fotogrametric",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="are_scanare_laser",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="bolta_peste_altar_structura",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                related_name="p_altar",
                to="nomenclatoare.MaterialeStructuraBolta",
                verbose_name="Structură boltă altar",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="bolta_peste_naos_structura",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                related_name="p_naos",
                to="nomenclatoare.MaterialeStructuraBolta",
                verbose_name="Structură boltă naos",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="bolta_peste_pronaos_structura",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                related_name="p_pronaos",
                to="nomenclatoare.MaterialeStructuraBolta",
                verbose_name="Structură boltă pronaos",
            ),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_clopote",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="descrierepage",
            name="numar_ochiesi",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="finisaj_exterior_tip",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="nomenclatoare.FinisajExterior", verbose_name="Finisaj exterior corp"
            ),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="fundatia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_biserici",
                to="nomenclatoare.tipfundatie",
                verbose_name="Structura fundației",
            ),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="tiranti_tip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_biserici",
                to="nomenclatoare.tiptiranti",
                verbose_name="Tip Tiranți",
            ),
        ),
        migrations.AlterField(
            model_name="istoricpage",
            name="are_mutari",
            field=models.BooleanField(default=False, verbose_name="Mutări"),
        ),
        migrations.AlterField(
            model_name="istoricpage",
            name="are_studiu_dendro",
            field=models.BooleanField(default=False, verbose_name="Studiu Dendrocronologic"),
        ),
        migrations.AlterField(
            model_name="istoricpage",
            name="lista_ctitori",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100),
                blank=True,
                null=True,
                size=20,
                verbose_name="Ctitori",
            ),
        ),
        migrations.AlterField(
            model_name="istoricpage",
            name="lista_mesteri",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100),
                blank=True,
                null=True,
                size=20,
                verbose_name="Meșteri",
            ),
        ),
        migrations.AlterField(
            model_name="istoricpage",
            name="lista_personalitati",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100),
                blank=True,
                null=True,
                size=20,
                verbose_name="Personalități",
            ),
        ),
        migrations.AlterField(
            model_name="istoricpage",
            name="lista_zugravi",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100),
                blank=True,
                null=True,
                size=20,
                verbose_name="Zugravi",
            ),
        ),
    ]
