# Generated by Django 3.1.13 on 2021-10-14 11:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20211014_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentaartisticapage',
            name='elemente_interventii',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=20),
        ),
    ]
