# Generated by Django 3.1.13 on 2021-10-14 13:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatoare', '0017_historicalmaterialestructurabolta_materialestructurabolta'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('app', '0065_componentaartisticapage_elemente_interventii'),
    ]

    operations = [
        migrations.AddField(
            model_name='bisericapage',
            name='datare_prin_interval_timp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bisericapage',
            name='datare_secol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_biserici', to='nomenclatoare.secol'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='elemente_interventii',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=20, verbose_name='Element'),
        ),
        migrations.CreateModel(
            name='PozeBiserica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('observatii', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Observații')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='poze', to='app.bisericapage')),
                ('poza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
