# Generated by Django 3.1.13 on 2021-10-18 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatoare', '0017_historicalmaterialestructurabolta_materialestructurabolta'),
        ('app', '0066_auto_20211014_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descrierepage',
            name='materiale',
        ),
        migrations.AddField(
            model_name='descrierepage',
            name='materiale',
            field=models.ForeignKey(blank=True, help_text='Materiale folosite in construcția bisericii', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.materialestructura'),
        ),
    ]
