# Generated by Django 3.1.13 on 2021-10-18 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatoare', '0017_historicalmaterialestructurabolta_materialestructurabolta'),
        ('app', '0067_auto_20211018_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bisericapage',
            name='adresa',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='bisericapage',
            name='conservare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bisericapage',
            name='judet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_biserici', to='nomenclatoare.judet', verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='bisericapage',
            name='latitudine',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitudine'),
        ),
        migrations.AlterField(
            model_name='bisericapage',
            name='localitate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_biserici', to='nomenclatoare.localitate', verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='bisericapage',
            name='longitudine',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitudine'),
        ),
        migrations.AlterField(
            model_name='bisericapage',
            name='prioritizare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bisericapage',
            name='valoare',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='adresa',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='judet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppp_biserici', to='nomenclatoare.judet', verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='latitudine',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitudine'),
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='localitate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.localitate', verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='longitudine',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitudine'),
        ),
    ]
