# Generated by Django 3.1.13 on 2021-10-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0075_pozefinisajeinvelitoareturle"),
    ]

    operations = [
        migrations.AddField(
            model_name="conservarepage",
            name="alte_elemente_importante_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="elemente_arhitecturale_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
        migrations.AddField(
            model_name="conservarepage",
            name="sit_pericol",
            field=models.BooleanField(default=False, verbose_name="Pericol"),
        ),
    ]
