# Generated by Django 3.1.13 on 2021-10-25 21:32

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_auto_20211022_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservarepage',
            name='turn_observatii',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Starea structurii turnului, inclusiv a tălpilor și a coifului', null=True, verbose_name='Observații'),
        ),
    ]
