# Generated by Django 3.1.13 on 2021-10-25 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatoare', '0022_auto_20211026_0112'),
        ('app', '0080_remove_descrierepage_turle_forma_sarpanta'),
    ]

    operations = [
        migrations.AddField(
            model_name='descrierepage',
            name='turle_stil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biserici', to='nomenclatoare.stilturle', verbose_name='Stilul turlelor'),
        ),
    ]
