# Generated by Django 3.1.13 on 2021-10-25 22:30

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatoare', '0027_historicalmaterialmasaaltar_materialmasaaltar'),
        ('app', '0085_auto_20211026_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentaartisticapage',
            name='altar_piciorul_mesei',
        ),
        migrations.RemoveField(
            model_name='componentaartisticapage',
            name='altar_placa_mesei',
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='altar_piciorul_mesei_new',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='p_piciorul_mesei', to='nomenclatoare.MaterialMasaAltar', verbose_name='Piciorul mesei'),
        ),
        migrations.AddField(
            model_name='componentaartisticapage',
            name='altar_placa_mesei_new',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='p_placa_mesei', to='nomenclatoare.MaterialMasaAltar', verbose_name='Placa mesei'),
        ),
    ]
