# Generated by Django 3.1.13 on 2021-10-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_auto_20211026_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descrierepage',
            name='bolta_peste_pronaos_material',
        ),
    ]
