# Generated by Django 3.1.13 on 2021-10-27 20:00

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0092_aboutpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="body",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="inchidere_tambur_turn_sindrila_grosime_medie",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (grosime medie)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="inchidere_tambur_turn_sindrila_latime_medie",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (lățime medie)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="inchidere_tambur_turn_sindrila_lungime",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (lungime)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="inchidere_tambur_turn_sindrila_pasul_baterii",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (pasul baterii)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="inchidere_tambur_turn_sindrila_pasul_latuirii",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (pasul lățuirii)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="invelitoare_corp_sindrila_grosime_medie",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (grosime medie)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="invelitoare_corp_sindrila_latime_medie",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (lățime medie)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="invelitoare_corp_sindrila_lungime",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (lungime)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="invelitoare_corp_sindrila_pasul_baterii",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (pasul baterii)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="invelitoare_corp_sindrila_pasul_latuirii",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (pasul lățuirii)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="invelitoare_turle_sindrila_grosime_medie",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (grosime medie)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="invelitoare_turle_sindrila_latime_medie",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (lățime medie)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="invelitoare_turle_sindrila_lungime",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (lungime)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="invelitoare_turle_sindrila_pasul_baterii",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (pasul baterii)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="invelitoare_turle_sindrila_pasul_latuirii",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (pasul lățuirii)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="invelitoare_turn_sindrila_grosime_medie",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (grosime medie)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="invelitoare_turn_sindrila_latime_medie",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (lățime medie)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="invelitoare_turn_sindrila_lungime",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (lungime)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="invelitoare_turn_sindrila_pasul_baterii",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (pasul baterii)"),
        ),
        migrations.AlterField(
            model_name="descrierepage",
            name="invelitoare_turn_sindrila_pasul_latuirii",
            field=models.FloatField(blank=True, null=True, verbose_name="Șindrila (pasul lățuirii)"),
        ),
        migrations.AlterField(
            model_name="valoarepage",
            name="valoare_sit_observatii",
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name="Observații"),
        ),
    ]
