# Generated by Django 3.1.13 on 2021-10-28 19:59

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension, TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_auto_20211027_2300'),
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension()
    ]
