# Generated by Django 3.1.13 on 2021-10-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0094_auto_20211028_2259"),
    ]

    operations = [
        migrations.AddField(
            model_name="bisericapage",
            name="utitle",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="UTitle"),
        ),
    ]
