# Generated by Django 3.1.13 on 2021-11-02 12:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0096_bisericapage_datare_an"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "paragraph_block",
                        wagtail.core.blocks.RichTextBlock(
                            features=["h2", "h3", "bold", "italic", "link", "ol", "ul", "document-link"],
                            icon="fa-paragraph",
                            template="blocks/paragraph_block.html",
                        ),
                    )
                ],
                blank=True,
                null=True,
                verbose_name="Page body",
            ),
        ),
    ]
