# Generated by Django 3.1.13 on 2021-11-05 09:42

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0100_auto_20211105_1127"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="pozeaccese",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozealtar",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozealteelementeimportante",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeamplasament",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozebolti",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeclopote",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozecor",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozecorpbiserica",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozecosoroabe",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozedescrierebolti",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeelementearhitecturale",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeelementesculptate",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeetapeanterioareinvelitoare",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeferestre",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozefinisajeexteriorcorp",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozefinisajeinchideretambur",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozefinisajeinvelitoare",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozefinisajeinvelitoareturle",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozefinisajeinvelitoareturn",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozefinisajexterior",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozefinisajperetiinteriori",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozefinisajtavanesibolti",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozefundatie",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozefundatii",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozegeneraleexterior",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozegeneraleinterior",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeicoanevechi",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeiconostas",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeinstalatieelectrica",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeinstalatietermica",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeinvelitoaresarpantasiturn",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozemasaatlar",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozemobilier",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozemobiliere",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeobiectedecult",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeobiectedecultconservare",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeobiecteinstrainate",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeochiesi",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeparatraznet",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozepardoseliinterioare",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozepeisagisticasitului",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeperetedespartitor",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozepicturaexterioara",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozepicturainterioara",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozepisanie",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeproscomidie",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozesarpanta",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozesarpantacorpbiserica",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozesit",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozesolee",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozestratpictural",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozestructuracatei",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozestructuracheotoare",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozestructuramixt",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozetalpi",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozetamplarii",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeteren",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozetiranti",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeturle",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeturn",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozeturnconservare",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozevegetatie",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pozezonadinjurulbiserici",
            managers=[
                ("cache", django.db.models.manager.Manager()),
            ],
        ),
    ]
