# Generated by Django 3.1.13 on 2021-11-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_auto_20211105_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozeaccese',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozealtar',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozealteelementeimportante',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeamplasament',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozebolti',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeclopote',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozecor',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozecorpbiserica',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozecosoroabe',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozedescrierebolti',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeelementearhitecturale',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeelementesculptate',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeetapeanterioareinvelitoare',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeferestre',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozefinisajeexteriorcorp',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozefinisajeinchideretambur',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozefinisajeinvelitoare',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozefinisajeinvelitoareturle',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozefinisajeinvelitoareturn',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozefinisajexterior',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozefinisajperetiinteriori',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozefinisajtavanesibolti',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozefundatie',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozefundatii',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozegeneraleexterior',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozegeneraleinterior',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeicoanevechi',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeiconostas',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeinstalatieelectrica',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeinstalatietermica',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeinvelitoaresarpantasiturn',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozemasaatlar',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozemobilier',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozemobiliere',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeobiectedecult',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeobiectedecultconservare',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeobiecteinstrainate',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeochiesi',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeparatraznet',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozepardoseliinterioare',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozepeisagisticasitului',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeperetedespartitor',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozepicturaexterioara',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozepicturainterioara',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozepisanie',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeproscomidie',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozesarpanta',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozesarpantacorpbiserica',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozesit',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozesolee',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozestratpictural',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozestructuracatei',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozestructuracheotoare',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozestructuramixt',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozetalpi',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozetamplarii',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeteren',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozetiranti',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeturle',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeturn',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozeturnconservare',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozevegetatie',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pozezonadinjurulbiserici',
            name='rendition',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
