# Generated by Django 3.1.13 on 2021-11-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0106_descrierepage_sistem_structural_observatii'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bisericapage',
            name='adresa',
        ),
        migrations.RemoveField(
            model_name='bisericapage',
            name='conservare',
        ),
        migrations.RemoveField(
            model_name='bisericapage',
            name='datare_an',
        ),
        migrations.RemoveField(
            model_name='bisericapage',
            name='datare_prin_interval_timp',
        ),
        migrations.RemoveField(
            model_name='bisericapage',
            name='datare_secol',
        ),
        migrations.RemoveField(
            model_name='bisericapage',
            name='judet',
        ),
        migrations.RemoveField(
            model_name='bisericapage',
            name='latitudine',
        ),
        migrations.RemoveField(
            model_name='bisericapage',
            name='localitate',
        ),
        migrations.RemoveField(
            model_name='bisericapage',
            name='longitudine',
        ),
        migrations.RemoveField(
            model_name='bisericapage',
            name='prioritizare',
        ),
        migrations.RemoveField(
            model_name='bisericapage',
            name='valoare',
        ),
        migrations.AddField(
            model_name='conservarepage',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='valoarepage',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
