# Generated by Django 3.1.13 on 2021-07-14 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0002_auto_20210714_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biserica',
            options={'verbose_name_plural': 'Biserici'},
        ),
        migrations.AlterModelOptions(
            name='functiunebiserica',
            options={'verbose_name_plural': 'Funcțiuni Biserică'},
        ),
        migrations.AlterModelOptions(
            name='identificare',
            options={'verbose_name_plural': 'Identificări Biserici'},
        ),
        migrations.AlterModelOptions(
            name='judet',
            options={'verbose_name_plural': 'Județe'},
        ),
        migrations.AlterModelOptions(
            name='localitate',
            options={'verbose_name_plural': 'Localități'},
        ),
        migrations.AlterField(
            model_name='identificare',
            name='cult',
            field=models.IntegerField(blank=True, choices=[(1, 'Biserica Ortodoxă Română'), (2, 'Biserica Română Unită cu Roma, Greco-Catolică'), (3, 'Biserica Romano-Catolică'), (4, 'Biserica Reformată din România'), (5, 'Episcopia Ortodoxă Sârbă de Timişoara'), (6, 'Arhiepiscopia Bisericii Armene'), (7, 'Biserica Ortodoxă de Rit Vechi din România'), (8, 'Biserica Evanghelică C.A. din România'), (9, 'Biserica Evanghelică Lutherană din România'), (10, 'Biserica Unitariană Maghiară'), (11, 'Cultul Creștin Baptist- Uniunea Bisericilor Creştine Baptiste din România'), (12, 'Biserica Creştină După Evanghelie din România'), (13, 'Biserica Evanghelică Română'), (14, 'Cultul Creștin Penticostal – Biserica lui Dumnezeu Apostolică din România'), (15, 'Biserica Adventistă de Ziua a Şaptea din România'), (16, 'Federaţia Comunităţilor Evreieşti din România- Cultul Mozaic'), (17, 'Cultul Musulman'), (18, 'Organizaţia Religioasă “Martorii lui Iehova”')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='identificare',
            name='functiune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biserici', to='biserici.functiunebiserica'),
        ),
        migrations.AlterField(
            model_name='identificare',
            name='functiune_initiala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biserici_initiale', to='biserici.functiunebiserica'),
        ),
        migrations.AlterField(
            model_name='identificare',
            name='judet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biserici', to='biserici.judet'),
        ),
        migrations.AlterField(
            model_name='identificare',
            name='localitate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biserici', to='biserici.localitate'),
        ),
        migrations.AlterField(
            model_name='identificare',
            name='singularitate',
            field=models.IntegerField(blank=True, choices=[(1, 'Singura biserică de același rit din localitate'), (2, 'Dublată')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='identificare',
            name='statut',
            field=models.IntegerField(blank=True, choices=[(1, 'Clasat UNESCO (importanță mondială)'), (2, 'Clasat Categoria A (importanță națională)'), (3, 'Clasat Categoria B (importanță regională)'), (4, 'Neclasat'), (5, 'În curs de clasare'), (6, 'În curs de declasare'), (7, 'Decalasat parțial')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='identificare',
            name='utilizare',
            field=models.IntegerField(blank=True, choices=[(1, 'Folosită permanent (săptămânal)'), (2, 'Folosită permanent (prin rotație)'), (3, 'Folosită ocazional'), (4, 'Nefolosită')], max_length=2, null=True),
        ),
    ]
