# Generated by Django 3.1.13 on 2021-07-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biserici", "0002_auto_20210729_1649"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="istoric",
            options={"verbose_name_plural": "Istoric Biserici"},
        ),
    ]
