# Generated by Django 3.1.13 on 2021-07-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0003_auto_20210714_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultBiserica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Culturi Biserică',
            },
        ),
        migrations.CreateModel(
            name='SingularitateBiserica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Singularități Biserică',
            },
        ),
        migrations.CreateModel(
            name='StatutBiserica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Statuturi Biserică',
            },
        ),
        migrations.CreateModel(
            name='UtilizareBiserica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Utilizări Biserică',
            },
        ),
        migrations.AlterField(
            model_name='identificare',
            name='judet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biserici', to='biserici.judet'),
        ),
        migrations.AlterField(
            model_name='identificare',
            name='localitate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biserici', to='biserici.localitate'),
        ),
        migrations.AlterField(
            model_name='identificare',
            name='cult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biserici', to='biserici.cultbiserica'),
        ),
        migrations.AlterField(
            model_name='identificare',
            name='singularitate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biserici', to='biserici.singularitatebiserica'),
        ),
        migrations.AlterField(
            model_name='identificare',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biserici', to='biserici.statutbiserica'),
        ),
        migrations.AlterField(
            model_name='identificare',
            name='utilizare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biserici', to='biserici.utilizarebiserica'),
        ),
    ]
