# Generated by Django 3.1.13 on 2021-07-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0004_auto_20210714_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultbiserica',
            name='nume',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='functiunebiserica',
            name='nume',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='singularitatebiserica',
            name='nume',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='statutbiserica',
            name='nume',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='utilizarebiserica',
            name='nume',
            field=models.CharField(max_length=150),
        ),
    ]
