# Generated by Django 3.1.13 on 2021-07-30 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0004_auto_20210729_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotografii',
            options={'verbose_name_plural': 'Fotografii'},
        ),
    ]
