# Generated by Django 3.1.13 on 2021-07-30 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "nomenclatoare",
            "0005_boltapestealtar_historicalboltapestealtar_historicaltipboltapestealtar_historicaltipboltapronaos_tip",
        ),
        ("biserici", "0005_auto_20210730_1034"),
    ]

    operations = [
        migrations.AddField(
            model_name="descriere",
            name="bolta_peste_altar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.boltapestealtar",
                verbose_name="Boltă peste altar",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="bolta_peste_altar_tip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.tipboltapestealtar",
                verbose_name="Tip bolta peste altar",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="bolta_peste_naos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bolta_peste_naos",
                to="nomenclatoare.tipboltapronaos",
                verbose_name="Boltă peste naos",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="bolta_peste_pronaos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bolta_peste_pronaos",
                to="nomenclatoare.tipboltapronaos",
                verbose_name="Boltă peste pronaos",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="clopote_an",
            field=models.IntegerField(blank=True, null=True, verbose_name="Clopote (an)"),
        ),
        migrations.AddField(
            model_name="descriere",
            name="clopote_inscriptie",
            field=models.TextField(blank=True, null=True, verbose_name="Clopote (Inscripție)"),
        ),
        migrations.AddField(
            model_name="descriere",
            name="detalii_materiale",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="descriere",
            name="finisaj_exterior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.finisajexterior",
                verbose_name="Finisajul exterior al corpului bisericii ",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="gabarit_exterior_al_talpilor",
            field=models.ImageField(
                blank=True,
                help_text="o schiță a planului tălpilor / elevației /  turnului / triunghiului șarpantei",
                null=True,
                upload_to="schite",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="masa_altar_material_blat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="masa_altar_blat",
                to="nomenclatoare.material",
                verbose_name="Sfânta masă a altarului (materialul blatului)",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="masa_altar_material_picior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="masa_altar_picior",
                to="nomenclatoare.material",
                verbose_name="Sfânta masă a altarului (materialul piciorului)",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="materiale",
            field=models.ManyToManyField(
                help_text="Materiale folosite in construcția bisericii", to="nomenclatoare.Material"
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="numar_accese",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr accese"),
        ),
        migrations.AddField(
            model_name="descriere",
            name="numar_geamuri",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr de geamuri"),
        ),
        migrations.AddField(
            model_name="descriere",
            name="oachiesi_aerisitoare",
            field=models.BooleanField(default=False, verbose_name="Ochieși / Aerisitoare "),
        ),
        migrations.AddField(
            model_name="descriere",
            name="oachiesi_aerisitoare_detalii",
            field=models.TextField(blank=True, null=True, verbose_name="Ochieși / Aerisitoare (observații)"),
        ),
        migrations.AddField(
            model_name="descriere",
            name="planimetria_bisericii",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nomenclatoare.planimetrie"
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="sarpanta_detalii",
            field=models.TextField(blank=True, null=True, verbose_name="Șarpantă (observații)"),
        ),
        migrations.AddField(
            model_name="descriere",
            name="sarpanta_material_cruci",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="material_cruci",
                to="nomenclatoare.material",
                verbose_name="Șarpantă (material cruci)",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="sarpanta_numar_cruci",
            field=models.IntegerField(blank=True, null=True, verbose_name="Șarpantă (număr cruci)"),
        ),
        migrations.AddField(
            model_name="descriere",
            name="sarpanta_numar_turnulete",
            field=models.IntegerField(blank=True, null=True, verbose_name="Șarpantă (număr turnulețe decorative)"),
        ),
        migrations.AddField(
            model_name="descriere",
            name="sarpanta_tip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.tipsarpanta",
                verbose_name="Șarpantă (tip)",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="sarpanta_veche_nefolosita",
            field=models.BooleanField(default=False, verbose_name="Șarpantă veche nefolosită sub șarpanta actuală"),
        ),
        migrations.AddField(
            model_name="descriere",
            name="solee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="descriere",
            name="turn_amplasare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.amplasareturn",
                verbose_name="Turn (amplasare)",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="turn_asezare_talpi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.asezaretalpaturn",
                verbose_name="Turn (așezarea tălpilor turnului în legătură cu butea bisericii)",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="turn_decor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.decorturn",
                verbose_name="Turn (decor)",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="turn_dimensiune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.dimensiuneturn",
                verbose_name="Turn (dimensiune)",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="turn_galerie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.galerieturn",
                verbose_name="Turn (galerie)",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="turn_numar",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr de turnuri"),
        ),
        migrations.AddField(
            model_name="descriere",
            name="turn_numar_arcade",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr arcade Turn deschis"),
        ),
        migrations.AddField(
            model_name="descriere",
            name="turn_numar_arcade_detalii",
            field=models.TextField(blank=True, null=True, verbose_name="Detalii arcade Turn deschis"),
        ),
        migrations.AddField(
            model_name="descriere",
            name="turn_numar_talpi",
            field=models.IntegerField(blank=True, null=True, verbose_name="Turn (număr de tălpi)"),
        ),
        migrations.AddField(
            model_name="descriere",
            name="turn_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.planturn",
                verbose_name="Turn (plan)",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="turn_relatie_talpi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.relatietalpaturn",
                verbose_name="Turn (relația dintre tălpile turnului)",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="turn_tip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomenclatoare.tipturn",
                verbose_name="Turn (tip)",
            ),
        ),
        migrations.AddField(
            model_name="fotografii",
            name="foto1",
            field=models.ManyToManyField(related_name="foto1", to="biserici.FotografieDetaliuPod"),
        ),
        migrations.AddField(
            model_name="fotografii",
            name="foto2",
            field=models.ManyToManyField(related_name="foto2", to="biserici.FotografieDetaliuPod"),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="bolta_peste_altar",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.boltapestealtar",
                verbose_name="Boltă peste altar",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="bolta_peste_altar_tip",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.tipboltapestealtar",
                verbose_name="Tip bolta peste altar",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="bolta_peste_naos",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.tipboltapronaos",
                verbose_name="Boltă peste naos",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="bolta_peste_pronaos",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.tipboltapronaos",
                verbose_name="Boltă peste pronaos",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="clopote_an",
            field=models.IntegerField(blank=True, null=True, verbose_name="Clopote (an)"),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="clopote_inscriptie",
            field=models.TextField(blank=True, null=True, verbose_name="Clopote (Inscripție)"),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="detalii_materiale",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="finisaj_exterior",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.finisajexterior",
                verbose_name="Finisajul exterior al corpului bisericii ",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="gabarit_exterior_al_talpilor",
            field=models.TextField(
                blank=True,
                help_text="o schiță a planului tălpilor / elevației /  turnului / triunghiului șarpantei",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="masa_altar_material_blat",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.material",
                verbose_name="Sfânta masă a altarului (materialul blatului)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="masa_altar_material_picior",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.material",
                verbose_name="Sfânta masă a altarului (materialul piciorului)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="numar_accese",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr accese"),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="numar_geamuri",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr de geamuri"),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="oachiesi_aerisitoare",
            field=models.BooleanField(default=False, verbose_name="Ochieși / Aerisitoare "),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="oachiesi_aerisitoare_detalii",
            field=models.TextField(blank=True, null=True, verbose_name="Ochieși / Aerisitoare (observații)"),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="planimetria_bisericii",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.planimetrie",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="sarpanta_detalii",
            field=models.TextField(blank=True, null=True, verbose_name="Șarpantă (observații)"),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="sarpanta_material_cruci",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.material",
                verbose_name="Șarpantă (material cruci)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="sarpanta_numar_cruci",
            field=models.IntegerField(blank=True, null=True, verbose_name="Șarpantă (număr cruci)"),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="sarpanta_numar_turnulete",
            field=models.IntegerField(blank=True, null=True, verbose_name="Șarpantă (număr turnulețe decorative)"),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="sarpanta_tip",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.tipsarpanta",
                verbose_name="Șarpantă (tip)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="sarpanta_veche_nefolosita",
            field=models.BooleanField(default=False, verbose_name="Șarpantă veche nefolosită sub șarpanta actuală"),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="solee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="turn_amplasare",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.amplasareturn",
                verbose_name="Turn (amplasare)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="turn_asezare_talpi",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.asezaretalpaturn",
                verbose_name="Turn (așezarea tălpilor turnului în legătură cu butea bisericii)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="turn_decor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.decorturn",
                verbose_name="Turn (decor)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="turn_dimensiune",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.dimensiuneturn",
                verbose_name="Turn (dimensiune)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="turn_galerie",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.galerieturn",
                verbose_name="Turn (galerie)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="turn_numar",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr de turnuri"),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="turn_numar_arcade",
            field=models.IntegerField(blank=True, null=True, verbose_name="Număr arcade Turn deschis"),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="turn_numar_arcade_detalii",
            field=models.TextField(blank=True, null=True, verbose_name="Detalii arcade Turn deschis"),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="turn_numar_talpi",
            field=models.IntegerField(blank=True, null=True, verbose_name="Turn (număr de tălpi)"),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="turn_plan",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.planturn",
                verbose_name="Turn (plan)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="turn_relatie_talpi",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.relatietalpaturn",
                verbose_name="Turn (relația dintre tălpile turnului)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="turn_tip",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.tipturn",
                verbose_name="Turn (tip)",
            ),
        ),
        migrations.CreateModel(
            name="Finisaj",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("biserica", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="biserici.biserica")),
            ],
            options={
                "verbose_name_plural": "Finisaje",
            },
        ),
        migrations.CreateModel(
            name="ComponentaArtistica",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("biserica", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="biserici.biserica")),
            ],
            options={
                "verbose_name_plural": "Componenta Artistică",
            },
        ),
    ]
