# Generated by Django 3.1.13 on 2021-07-14 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0005_auto_20210714_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProprietateBiserica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Proprietăți Biserică',
            },
        ),
        migrations.AddField(
            model_name='identificare',
            name='proprietate_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identificare',
            name='proprietate_actuala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biserici_initiale', to='biserici.proprietatebiserica'),
        ),
    ]
