# Generated by Django 3.1.13 on 2021-07-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0006_auto_20210714_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificare',
            name='inscriere_documente_cadastrale',
            field=models.IntegerField(blank=True, choices=[(1, 'Da'), (2, 'Nu'), (3, 'În curs de')], null=True),
        ),
        migrations.AddField(
            model_name='identificare',
            name='proprietar_actual',
            field=models.TextField(blank=True, null=True),
        ),
    ]
