# Generated by Django 3.1.13 on 2021-07-30 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "nomenclatoare",
            "0005_boltapestealtar_historicalboltapestealtar_historicaltipboltapestealtar_historicaltipboltapronaos_tip",
        ),
        ("biserici", "0007_auto_20210730_1413"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestFoto",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("poza", models.ImageField(max_length=250, upload_to="fotografii")),
                ("detalii", models.TextField(blank=True, null=True)),
                ("copyright", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "detaliu",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="nomenclatoare.detaliupodturn"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="fotografii",
            name="foto1",
            field=models.ManyToManyField(blank=True, null=True, related_name="foto1", to="biserici.TestFoto"),
        ),
        migrations.AlterField(
            model_name="fotografii",
            name="foto2",
            field=models.ManyToManyField(blank=True, null=True, related_name="foto2", to="biserici.TestFoto"),
        ),
    ]
