# Generated by Django 3.1.13 on 2021-07-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0008_auto_20210730_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografii',
            name='foto1',
        ),
        migrations.RemoveField(
            model_name='fotografii',
            name='foto2',
        ),
        migrations.DeleteModel(
            name='TestFoto',
        ),
    ]
