# Generated by Django 3.1.13 on 2021-07-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0011_auto_20210714_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stareconservare',
            name='biserica',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conservare', to='biserici.biserica'),
        ),
        migrations.AlterField(
            model_name='valoarepatrimoniucultural',
            name='biserica',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patrimoniu', to='biserici.biserica'),
        ),
    ]
