# Generated by Django 3.1.13 on 2021-07-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatoare', '0005_boltapestealtar_historicalboltapestealtar_historicaltipboltapestealtar_historicaltipboltapronaos_tip'),
        ('biserici', '0012_auto_20210730_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinisajActualInvelitoare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sindrila_lungime', models.IntegerField(blank=True, null=True)),
                ('sindrila_latime_medie', models.IntegerField(blank=True, null=True)),
                ('sindrila_grosime_medie', models.IntegerField(blank=True, null=True)),
                ('sindrila_pasul_latuirii', models.IntegerField(blank=True, null=True)),
                ('sindrila_pasul_baterii', models.IntegerField(blank=True, null=True)),
                ('sindrila_numar_straturi', models.IntegerField(blank=True, null=True)),
                ('sindrila_cu_horj', models.BooleanField(default=False)),
                ('sindrila_cu_tesitura', models.BooleanField(default=False)),
                ('finisaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finisaje_actuale', to='biserici.finisaj')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.finisajexterior')),
                ('sindrlia_esenta_lemnoasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.esentalemnoasa')),
                ('sindrlia_forma_botului', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tipbotsindrila')),
                ('sindrlia_prelucrare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tipprelucraresindrila')),
                ('sindrlia_tipul_de_batere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tipbateresindrila')),
                ('sindrlia_tipul_prindere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tipprinderesindrila')),
            ],
        ),
        migrations.CreateModel(
            name='FinisajAnteriorInvelitoare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape_anterioare_vizibile', models.BooleanField(default=False)),
                ('sindrila_pasul_latuirii', models.IntegerField(blank=True, null=True)),
                ('sindrila_numar_straturi', models.IntegerField(blank=True, null=True)),
                ('sindrila_cu_horj', models.BooleanField(default=False)),
                ('sindrila_cu_tesitura', models.BooleanField(default=False)),
                ('alte_tipuri_invelitoare', models.TextField(blank=True, null=True)),
                ('finisaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finisaje_anterioare', to='biserici.finisaj')),
                ('sindrlia_esenta_lemnoasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.esentalemnoasa')),
                ('sindrlia_forma_botului', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tipbotsindrila')),
                ('sindrlia_tipul_de_batere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tipbateresindrila')),
            ],
        ),
        migrations.CreateModel(
            name='FinisajBolti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observatii', models.TextField(blank=True, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.elementbiserica')),
                ('finisaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finisaje_bolti', to='biserici.finisaj')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.finisaj')),
            ],
        ),
        migrations.CreateModel(
            name='FinisajInvelitoareTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sindrila_lungime', models.IntegerField(blank=True, null=True)),
                ('sindrila_latime_medie', models.IntegerField(blank=True, null=True)),
                ('sindrila_grosime_medie', models.IntegerField(blank=True, null=True)),
                ('sindrila_pasul_latuirii', models.IntegerField(blank=True, null=True)),
                ('sindrila_pasul_baterii', models.IntegerField(blank=True, null=True)),
                ('sindrila_numar_straturi', models.IntegerField(blank=True, null=True)),
                ('sindrila_cu_horj', models.BooleanField(default=False)),
                ('sindrila_cu_tesitura', models.BooleanField(default=False)),
                ('finisaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finisaje_invelitoare_turn', to='biserici.finisaj')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.finisajexterior')),
                ('sindrlia_esenta_lemnoasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.esentalemnoasa')),
                ('sindrlia_forma_botului', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tipbotsindrila')),
                ('sindrlia_prelucrare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tipprelucraresindrila')),
                ('sindrlia_tipul_de_batere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tipbateresindrila')),
                ('sindrlia_tipul_prindere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tipprinderesindrila')),
            ],
        ),
        migrations.CreateModel(
            name='FinisajPardosea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observatii', models.TextField(blank=True, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.elementbiserica')),
                ('finisaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finisaje_pardosea', to='biserici.finisaj')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.materialfinisajpardoseli')),
            ],
        ),
        migrations.CreateModel(
            name='FinisajPeretiInterior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observatii', models.TextField(blank=True, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.elementbiserica')),
                ('finisaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finisaje_pereti_interiori', to='biserici.finisaj')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.materialfinisajperetiinteriori')),
            ],
        ),
        migrations.CreateModel(
            name='FinisajTamburTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sindrila_lungime', models.IntegerField(blank=True, null=True)),
                ('sindrila_latime_medie', models.IntegerField(blank=True, null=True)),
                ('sindrila_grosime_medie', models.IntegerField(blank=True, null=True)),
                ('sindrila_pasul_latuirii', models.IntegerField(blank=True, null=True)),
                ('sindrila_pasul_baterii', models.IntegerField(blank=True, null=True)),
                ('sindrila_numar_straturi', models.IntegerField(blank=True, null=True)),
                ('sindrila_cu_horj', models.BooleanField(default=False)),
                ('sindrila_cu_tesitura', models.BooleanField(default=False)),
                ('finisaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finisaje_tambur_turn', to='biserici.finisaj')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.finisajexterior')),
                ('sindrlia_esenta_lemnoasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.esentalemnoasa')),
                ('sindrlia_forma_botului', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tipbotsindrila')),
                ('sindrlia_prelucrare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tipprelucraresindrila')),
                ('sindrlia_tipul_de_batere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tipbateresindrila')),
                ('sindrlia_tipul_prindere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tipprinderesindrila')),
            ],
        ),
        migrations.CreateModel(
            name='FinisajTavan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observatii', models.TextField(blank=True, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.elementbiserica')),
                ('finisaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finisaje_tavan', to='biserici.finisaj')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.finisaj')),
            ],
        ),
        migrations.DeleteModel(
            name='FinisajInvelitoare',
        ),
    ]
