# Generated by Django 3.1.13 on 2021-07-15 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0012_auto_20210714_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='istoric',
            name='ctitor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='istoric',
            name='mesteri',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='istoric',
            name='personalitati',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='istoric',
            name='pisanie',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='istoric',
            name='zugravi',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='MutareBiserica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitudine', models.FloatField(blank=True, null=True)),
                ('longitudine', models.FloatField(blank=True, null=True)),
                ('localitate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biserici.localitate')),
            ],
        ),
        migrations.AddField(
            model_name='istoric',
            name='mutari',
            field=models.ManyToManyField(to='biserici.MutareBiserica'),
        ),
    ]
