# Generated by Django 3.1.13 on 2021-07-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0013_auto_20210715_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='istoric',
            name='mutari',
        ),
        migrations.AddField(
            model_name='mutarebiserica',
            name='istoric',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='biserici.istoric'),
            preserve_default=False,
        ),
    ]
