# Generated by Django 3.1.13 on 2021-07-21 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biserici', '0014_auto_20210715_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conservare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
                ('biserica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biserici.biserica')),
                ('last_edit_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stare conservare Biserici',
            },
        ),
        migrations.CreateModel(
            name='Patrimoniu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
                ('biserica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biserici.biserica')),
                ('last_edit_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Valoare patrimoniu cultural Biserici',
            },
        ),
        migrations.RemoveField(
            model_name='valoarepatrimoniucultural',
            name='biserica',
        ),
        migrations.RemoveField(
            model_name='valoarepatrimoniucultural',
            name='last_edit_user',
        ),
        migrations.AlterField(
            model_name='istoric',
            name='ctitor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='istoric',
            name='mesteri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='istoric',
            name='personalitati',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='istoric',
            name='pisanie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='istoric',
            name='zugravi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='StareConservare',
        ),
        migrations.DeleteModel(
            name='ValoarePatrimoniuCultural',
        ),
    ]
