# Generated by Django 3.1.13 on 2021-07-30 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "nomenclatoare",
            "0005_boltapestealtar_historicalboltapestealtar_historicaltipboltapestealtar_historicaltipboltapronaos_tip",
        ),
        (
            "biserici",
            "0014_historicalcomponentaartistica_historicalfinisaj_historicalfinisajactualinvelitoare_historicalfinisaj",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="descriere",
            name="fundatia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biserici",
                to="nomenclatoare.tipfundatie",
                verbose_name="Fundația",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="sistem_in_catei",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biserici",
                to="nomenclatoare.historicaltipstructuracatei",
                verbose_name="Sistem structural al corpului bisericii În căței",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="sistem_in_cheotoare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biserici",
                to="nomenclatoare.tipstructuracheotoare",
                verbose_name="Sistem structural al corpului bisericii În cheotoare",
            ),
        ),
        migrations.AddField(
            model_name="descriere",
            name="sistem_mixt",
            field=models.TextField(blank=True, null=True, verbose_name="Sistem structural al corpului bisericii mixt"),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="fundatia",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.tipfundatie",
                verbose_name="Fundația",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="sistem_in_catei",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.historicaltipstructuracatei",
                verbose_name="Sistem structural al corpului bisericii În căței",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="sistem_in_cheotoare",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.tipstructuracheotoare",
                verbose_name="Sistem structural al corpului bisericii În cheotoare",
            ),
        ),
        migrations.AddField(
            model_name="historicaldescriere",
            name="sistem_mixt",
            field=models.TextField(blank=True, null=True, verbose_name="Sistem structural al corpului bisericii mixt"),
        ),
        migrations.AlterField(
            model_name="descriere",
            name="bolta_peste_altar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biserici",
                to="nomenclatoare.boltapestealtar",
                verbose_name="Boltă peste altar",
            ),
        ),
        migrations.AlterField(
            model_name="descriere",
            name="bolta_peste_altar_tip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biserici",
                to="nomenclatoare.tipboltapestealtar",
                verbose_name="Tip bolta peste altar",
            ),
        ),
        migrations.AlterField(
            model_name="descriere",
            name="bolta_peste_naos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biserici_bolta_peste_naos",
                to="nomenclatoare.tipboltapronaos",
                verbose_name="Boltă peste naos",
            ),
        ),
        migrations.AlterField(
            model_name="descriere",
            name="bolta_peste_pronaos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biserici_bolta_peste_pronaos",
                to="nomenclatoare.tipboltapronaos",
                verbose_name="Boltă peste pronaos",
            ),
        ),
    ]
