# Generated by Django 3.1.13 on 2021-07-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0015_auto_20210721_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='SursaDatare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='mutarebiserica',
            name='istoric',
        ),
        migrations.AddField(
            model_name='istoric',
            name='mutari_biserica',
            field=models.ManyToManyField(to='biserici.MutareBiserica'),
        ),
        migrations.AddField(
            model_name='istoric',
            name='sursa_datare',
            field=models.ManyToManyField(to='biserici.SursaDatare'),
        ),
    ]
