# Generated by Django 3.1.13 on 2021-07-30 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatoare', '0005_boltapestealtar_historicalboltapestealtar_historicaltipboltapestealtar_historicaltipboltapronaos_tip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biserici', '0016_auto_20210730_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentaartistica',
            name='altar_decor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decoruri_altar', to='nomenclatoare.finisajiconostas'),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='altar_decor_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='alte_icoane_vechi',
            field=models.BooleanField(default=False, verbose_name='Elemente sculptate / decoruri în biserică'),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='alte_icoane_vechi_detalii',
            field=models.TextField(blank=True, help_text='Elemente sculptate / decoruri în biserică', null=True),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='elemente_detalii',
            field=models.TextField(blank=True, help_text='Elemente sculptate / decoruri în biserică', null=True),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='elemente_sculptate',
            field=models.BooleanField(default=False, verbose_name='Elemente sculptate / decoruri în biserică'),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='iconostas_naos_altar_detalii',
            field=models.TextField(blank=True, help_text='Particularități ale iconostasului ce merită a fi precizate (de urmărit care este standardul de iconostas în zonă și care sunt eventualele deviații de la standard', null=True),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='iconostas_naos_altar_finisaj',
            field=models.ManyToManyField(blank=True, related_name='iconostasuri_naos_altar', to='nomenclatoare.FinisajIconostas'),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='iconostas_naos_altar_numar_intrari',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='iconostas_naos_altar_tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iconostasuri_naos_altar', to='nomenclatoare.tipiconostas'),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='iconostas_pronaos_naos_detalii',
            field=models.TextField(blank=True, help_text='Particularități ale iconostasului ce merită a fi precizate (de urmărit care este standardul de iconostas în zonă și care sunt eventualele deviații de la standard', null=True),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='iconostas_pronaos_naos_finisaj',
            field=models.ManyToManyField(blank=True, related_name='iconostasuri_pronaos_naos', to='nomenclatoare.FinisajIconostas'),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='iconostas_pronaos_naos_numar_intrari',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='iconostas_pronaos_naos_tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iconostasuri_pronaos_naos', to='nomenclatoare.tipiconostas'),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='mobiliere',
            field=models.BooleanField(default=False, verbose_name='Mobilier / candelabre /lumânărare / sfeșnice'),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='mobiliere_detalii',
            field=models.TextField(blank=True, help_text='Mobilier / candelabre /lumânărare / sfeșnice', null=True),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='obiecte_de_cult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='obiecte_de_cult_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='obiecte_instrainate',
            field=models.BooleanField(default=False, verbose_name='Obiecte de cult înstrăinate'),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='obiecte_instrainate_detalii',
            field=models.TextField(blank=True, help_text='Observații privind înstrăinarea obiectelor de cult aparținătoare bisericii ', null=True),
        ),
        migrations.AddField(
            model_name='componentaartistica',
            name='proscomidie',
            field=models.BooleanField(default=False, verbose_name='Proscomidie în exteriorul altarului'),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='altar_decor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomenclatoare.finisajiconostas'),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='altar_decor_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='alte_icoane_vechi',
            field=models.BooleanField(default=False, verbose_name='Elemente sculptate / decoruri în biserică'),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='alte_icoane_vechi_detalii',
            field=models.TextField(blank=True, help_text='Elemente sculptate / decoruri în biserică', null=True),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='elemente_detalii',
            field=models.TextField(blank=True, help_text='Elemente sculptate / decoruri în biserică', null=True),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='elemente_sculptate',
            field=models.BooleanField(default=False, verbose_name='Elemente sculptate / decoruri în biserică'),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='iconostas_naos_altar_detalii',
            field=models.TextField(blank=True, help_text='Particularități ale iconostasului ce merită a fi precizate (de urmărit care este standardul de iconostas în zonă și care sunt eventualele deviații de la standard', null=True),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='iconostas_naos_altar_numar_intrari',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='iconostas_naos_altar_tip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomenclatoare.tipiconostas'),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='iconostas_pronaos_naos_detalii',
            field=models.TextField(blank=True, help_text='Particularități ale iconostasului ce merită a fi precizate (de urmărit care este standardul de iconostas în zonă și care sunt eventualele deviații de la standard', null=True),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='iconostas_pronaos_naos_numar_intrari',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='iconostas_pronaos_naos_tip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomenclatoare.tipiconostas'),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='mobiliere',
            field=models.BooleanField(default=False, verbose_name='Mobilier / candelabre /lumânărare / sfeșnice'),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='mobiliere_detalii',
            field=models.TextField(blank=True, help_text='Mobilier / candelabre /lumânărare / sfeșnice', null=True),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='obiecte_de_cult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='obiecte_de_cult_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='obiecte_instrainate',
            field=models.BooleanField(default=False, verbose_name='Obiecte de cult înstrăinate'),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='obiecte_instrainate_detalii',
            field=models.TextField(blank=True, help_text='Observații privind înstrăinarea obiectelor de cult aparținătoare bisericii ', null=True),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='proscomidie',
            field=models.BooleanField(default=False, verbose_name='Proscomidie în exteriorul altarului'),
        ),
        migrations.AlterField(
            model_name='descriere',
            name='elemente',
            field=models.ManyToManyField(blank=True, help_text='Elemente ansamblu construit', to='nomenclatoare.ElementBiserica'),
        ),
        migrations.AlterField(
            model_name='descriere',
            name='elemente_importante',
            field=models.ManyToManyField(blank=True, help_text='Elemente ansamblu construit', to='nomenclatoare.ElementImportant'),
        ),
        migrations.AlterField(
            model_name='descriere',
            name='materiale',
            field=models.ManyToManyField(blank=True, help_text='Materiale folosite in construcția bisericii', to='nomenclatoare.Material'),
        ),
        migrations.AlterField(
            model_name='descriere',
            name='peisagistica_sitului',
            field=models.ManyToManyField(blank=True, to='nomenclatoare.PeisagisticaSit'),
        ),
        migrations.AlterField(
            model_name='finisaj',
            name='finisaj_exterior_tip',
            field=models.ManyToManyField(blank=True, to='nomenclatoare.FinisajExterior'),
        ),
        migrations.AlterField(
            model_name='istoric',
            name='ctitori',
            field=models.ManyToManyField(blank=True, related_name='ctitor', through='nomenclatoare.CtitorBiserica', to='nomenclatoare.Persoana'),
        ),
        migrations.AlterField(
            model_name='istoric',
            name='evenimente',
            field=models.ManyToManyField(blank=True, through='nomenclatoare.EvenimentBiserica', to='nomenclatoare.Eveniment'),
        ),
        migrations.AlterField(
            model_name='istoric',
            name='mesteri',
            field=models.ManyToManyField(blank=True, related_name='mester', through='nomenclatoare.MesterBiserica', to='nomenclatoare.Persoana'),
        ),
        migrations.AlterField(
            model_name='istoric',
            name='mutari_biserica',
            field=models.ManyToManyField(blank=True, through='nomenclatoare.MutareBiserica', to='nomenclatoare.Localitate'),
        ),
        migrations.AlterField(
            model_name='istoric',
            name='personalitati',
            field=models.ManyToManyField(blank=True, related_name='personalitate', through='nomenclatoare.PersonalitateBiserica', to='nomenclatoare.Persoana'),
        ),
        migrations.AlterField(
            model_name='istoric',
            name='zugravi',
            field=models.ManyToManyField(blank=True, related_name='zugrav', through='nomenclatoare.ZugravBiserica', to='nomenclatoare.Persoana'),
        ),
        migrations.CreateModel(
            name='PicturaInterioara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizare_detalii', models.TextField(blank=True, null=True)),
                ('numar_straturi_pictura', models.IntegerField(blank=True, null=True)),
                ('anul_picturii', models.IntegerField(blank=True, null=True)),
                ('datare_prin_interval_timp', models.CharField(blank=True, max_length=50, null=True)),
                ('datare_detalii', models.TextField(blank=True, null=True)),
                ('componenta_artistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biserici.componentaartistica')),
                ('datare_secol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localizari_interioare', to='nomenclatoare.secol')),
                ('localizare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localizari_interioare', to='nomenclatoare.localizarepictura')),
                ('sursa_datare', models.ManyToManyField(blank=True, related_name='componente_artistice_interioare', to='nomenclatoare.SursaDatare')),
                ('tehnica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tehnicapictura')),
            ],
        ),
        migrations.CreateModel(
            name='PicturaExterioara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizare_detalii', models.TextField(blank=True, null=True)),
                ('numar_straturi_pictura', models.IntegerField(blank=True, null=True)),
                ('anul_picturii', models.IntegerField(blank=True, null=True)),
                ('datare_prin_interval_timp', models.CharField(blank=True, max_length=50, null=True)),
                ('datare_detalii', models.TextField(blank=True, null=True)),
                ('componenta_artistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biserici.componentaartistica')),
                ('datare_secol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localizari_exterioare', to='nomenclatoare.secol')),
                ('localizare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localizari_exterioare', to='nomenclatoare.localizarepictura')),
                ('sursa_datare', models.ManyToManyField(blank=True, related_name='componente_artistice_exterioare', to='nomenclatoare.SursaDatare')),
                ('tehnica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tehnicapictura')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPicturaInterioara',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('localizare_detalii', models.TextField(blank=True, null=True)),
                ('numar_straturi_pictura', models.IntegerField(blank=True, null=True)),
                ('anul_picturii', models.IntegerField(blank=True, null=True)),
                ('datare_prin_interval_timp', models.CharField(blank=True, max_length=50, null=True)),
                ('datare_detalii', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('componenta_artistica', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='biserici.componentaartistica')),
                ('datare_secol', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomenclatoare.secol')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('localizare', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomenclatoare.localizarepictura')),
                ('tehnica', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomenclatoare.tehnicapictura')),
            ],
            options={
                'verbose_name': 'historical pictura interioara',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPicturaExterioara',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('localizare_detalii', models.TextField(blank=True, null=True)),
                ('numar_straturi_pictura', models.IntegerField(blank=True, null=True)),
                ('anul_picturii', models.IntegerField(blank=True, null=True)),
                ('datare_prin_interval_timp', models.CharField(blank=True, max_length=50, null=True)),
                ('datare_detalii', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('componenta_artistica', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='biserici.componentaartistica')),
                ('datare_secol', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomenclatoare.secol')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('localizare', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomenclatoare.localizarepictura')),
                ('tehnica', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomenclatoare.tehnicapictura')),
            ],
            options={
                'verbose_name': 'historical pictura exterioara',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
