# Generated by Django 3.1.13 on 2021-07-28 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0016_auto_20210728_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eveniment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Persoana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Secol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Studiu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=150)),
                ('fisier', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StudiuDendocronologic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=150)),
                ('fisier', models.FileField(upload_to='')),
                ('an', models.IntegerField()),
                ('autor', models.CharField(max_length=150)),
                ('detalii', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='istoric',
            name='ctitor',
        ),
        migrations.RemoveField(
            model_name='istoric',
            name='mesteri',
        ),
        migrations.RemoveField(
            model_name='istoric',
            name='mutari_biserica',
        ),
        migrations.RemoveField(
            model_name='istoric',
            name='personalitati',
        ),
        migrations.RemoveField(
            model_name='istoric',
            name='pisanie',
        ),
        migrations.RemoveField(
            model_name='istoric',
            name='sursa_datare',
        ),
        migrations.RemoveField(
            model_name='istoric',
            name='zugravi',
        ),
        migrations.AddField(
            model_name='mutarebiserica',
            name='istoric',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='biserici.istoric'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ZugravBiserica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalii', models.TextField()),
                ('sursa', models.TextField()),
                ('istoric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biserici.istoric')),
                ('persoana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biserici.persoana')),
            ],
        ),
        migrations.CreateModel(
            name='StudiuIstoric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drepturi_de_autor', models.TextField()),
                ('istoric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biserici.istoric')),
                ('studiu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biserici.studiu')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalitateBiserica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalii', models.TextField()),
                ('sursa', models.TextField()),
                ('istoric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biserici.istoric')),
                ('persoana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biserici.persoana')),
            ],
        ),
        migrations.CreateModel(
            name='MesterBiserica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalii', models.TextField()),
                ('sursa', models.TextField()),
                ('istoric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biserici.istoric')),
                ('persoana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biserici.persoana')),
            ],
        ),
        migrations.CreateModel(
            name='EvenimentIstoric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalii', models.TextField()),
                ('sursa', models.TextField()),
                ('eveniment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biserici.eveniment')),
                ('istoric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biserici.istoric')),
            ],
        ),
        migrations.CreateModel(
            name='CtitorBiserica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalii', models.TextField()),
                ('sursa', models.TextField()),
                ('istoric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biserici.istoric')),
                ('persoana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biserici.persoana')),
            ],
        ),
    ]
