# Generated by Django 3.1.13 on 2021-07-28 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0018_auto_20210728_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultbiserica',
            options={'verbose_name_plural': '_Culturi Biserică'},
        ),
        migrations.AlterModelOptions(
            name='functiunebiserica',
            options={'verbose_name_plural': '_Funcțiuni Biserică'},
        ),
        migrations.AlterModelOptions(
            name='judet',
            options={'verbose_name_plural': '_Județe'},
        ),
        migrations.AlterModelOptions(
            name='localitate',
            options={'verbose_name_plural': '_Localități'},
        ),
        migrations.AlterModelOptions(
            name='proprietatebiserica',
            options={'verbose_name_plural': '_Proprietăți Biserică'},
        ),
        migrations.AlterModelOptions(
            name='singularitatebiserica',
            options={'verbose_name_plural': '_Singularități Biserică'},
        ),
        migrations.AlterModelOptions(
            name='statutbiserica',
            options={'verbose_name_plural': '_Statuturi Biserică'},
        ),
        migrations.AlterModelOptions(
            name='utilizarebiserica',
            options={'verbose_name_plural': '_Utilizări Biserică'},
        ),
        migrations.AlterField(
            model_name='istoric',
            name='datare_secol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biserici', to='biserici.secol'),
        ),
        migrations.AlterField(
            model_name='istoric',
            name='sursa_datare',
            field=models.ManyToManyField(related_name='biserici', to='biserici.SursaDatare'),
        ),
        migrations.AlterField(
            model_name='secol',
            name='nume',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='studiudendocronologic',
            name='an',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studiudendocronologic',
            name='autor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='studiudendocronologic',
            name='detalii',
            field=models.TextField(blank=True, null=True),
        ),
    ]
