# Generated by Django 3.1.13 on 2021-07-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0019_auto_20210728_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvenimentIstoric',
            new_name='EvenimentBiserica',
        ),
        migrations.AlterModelOptions(
            name='ctitorbiserica',
            options={'verbose_name_plural': 'Ctitori'},
        ),
        migrations.AlterModelOptions(
            name='eveniment',
            options={'verbose_name_plural': '_Evenimente'},
        ),
        migrations.AlterModelOptions(
            name='evenimentbiserica',
            options={'verbose_name_plural': 'Evenimente Istorice'},
        ),
        migrations.AlterModelOptions(
            name='mesterbiserica',
            options={'verbose_name_plural': 'Meșteri'},
        ),
        migrations.AlterModelOptions(
            name='mutarebiserica',
            options={'verbose_name_plural': '_Mutări Biserică'},
        ),
        migrations.AlterModelOptions(
            name='persoana',
            options={'verbose_name_plural': '_Persoane'},
        ),
        migrations.AlterModelOptions(
            name='personalitatebiserica',
            options={'verbose_name_plural': '_Personalități Biserică'},
        ),
        migrations.AlterModelOptions(
            name='secol',
            options={'verbose_name_plural': '_Secole'},
        ),
        migrations.AlterModelOptions(
            name='studiu',
            options={'verbose_name_plural': '_Studii'},
        ),
        migrations.AlterModelOptions(
            name='studiudendocronologic',
            options={'verbose_name_plural': '_Studii dendocronologice'},
        ),
        migrations.AlterModelOptions(
            name='studiuistoric',
            options={'verbose_name_plural': 'Studii Istorice'},
        ),
        migrations.AlterModelOptions(
            name='sursadatare',
            options={'verbose_name_plural': '_Surse Datări'},
        ),
        migrations.AlterModelOptions(
            name='zugravbiserica',
            options={'verbose_name_plural': 'Zugravi'},
        ),
    ]
