# Generated by Django 3.1.13 on 2021-07-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0020_auto_20210728_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studiu2Istoric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=150)),
                ('fisier', models.FileField(upload_to='')),
                ('drepturi_de_autor', models.TextField()),
                ('istoric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biserici.istoric')),
            ],
            options={
                'verbose_name_plural': 'Studii Istorice2',
            },
        ),
    ]
