# Generated by Django 3.1.13 on 2021-07-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0021_studiu2istoric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='istoric',
            name='studii_anterioare',
        ),
        migrations.DeleteModel(
            name='StudiuIstoric',
        ),
    ]
