# Generated by Django 3.1.13 on 2021-07-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0022_auto_20210728_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studiu2Istoric',
            new_name='StudiuIstoric',
        ),
        migrations.AlterModelOptions(
            name='studiuistoric',
            options={'verbose_name_plural': 'Studii Istorice'},
        ),
    ]
