# Generated by Django 3.1.13 on 2021-07-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0023_auto_20210728_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservare',
            name='stare_icoanelor_istorice',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_icoanelor_istorice_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='starea_mobilierului',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='starea_mobilierului_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='starea_obiectelor_de_cult',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='starea_obiectelor_de_cult_detalii',
            field=models.TextField(blank=True, null=True),
        ),
    ]
