# Generated by Django 3.1.13 on 2021-08-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biserici", "0023_auto_20210731_2005"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biserica",
            options={"ordering": ["the_order"], "verbose_name_plural": " Biserici"},
        ),
        migrations.AlterModelOptions(
            name="componentaartistica",
            options={"ordering": ["biserica__the_order"], "verbose_name_plural": "3.3 Componenta Artistică"},
        ),
        migrations.AlterModelOptions(
            name="conservare",
            options={"ordering": ["biserica__the_order"], "verbose_name_plural": "5. Stare de conservare"},
        ),
        migrations.AlterModelOptions(
            name="descriere",
            options={"ordering": ["biserica__the_order"], "verbose_name_plural": "3. Descriere"},
        ),
        migrations.AlterModelOptions(
            name="finisaj",
            options={"ordering": ["biserica__the_order"], "verbose_name_plural": "3.2 Finisaje"},
        ),
        migrations.AlterModelOptions(
            name="fotografii",
            options={"ordering": ["biserica__the_order"], "verbose_name_plural": "3.1 Fotografii"},
        ),
        migrations.AlterModelOptions(
            name="identificare",
            options={"ordering": ["biserica__the_order"], "verbose_name_plural": "1. Identificare"},
        ),
        migrations.AlterModelOptions(
            name="istoric",
            options={"ordering": ["biserica__the_order"], "verbose_name_plural": "2. Istoric"},
        ),
        migrations.AlterModelOptions(
            name="patrimoniu",
            options={"ordering": ["biserica__the_order"], "verbose_name_plural": "4. Valoare Patrimoniu Cultural"},
        ),
        migrations.AddField(
            model_name="historicalidentificare",
            name="adresa",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="identificare",
            name="adresa",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_bolti",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_cimitir",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_corp_biserica",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_elemente_arhitecturale",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_finisaj_peste_corp",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_finisaj_tambur_turn",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_fundatii",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_icoane_istorice",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_invelitoare",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_monumente_funerare_valoroase",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_pardoseli_interioare",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_picturi_exterioare",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_picturi_interioare",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_sarpanta_peste_corp_biserica",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_structura_turn",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_teren",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="stare_usi_si_ferestre",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="starea_mobilier",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="starea_obiecte_de_cult",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="conservare",
            name="vegetatie_invaziva",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_bolti",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_cimitir",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_corp_biserica",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_elemente_arhitecturale",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_finisaj_peste_corp",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_finisaj_tambur_turn",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_fundatii",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_icoane_istorice",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_invelitoare",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_monumente_funerare_valoroase",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_pardoseli_interioare",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_picturi_exterioare",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_picturi_interioare",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_sarpanta_peste_corp_biserica",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_structura_turn",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_teren",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="stare_usi_si_ferestre",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="starea_mobilier",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="starea_obiecte_de_cult",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name="historicalconservare",
            name="vegetatie_invaziva",
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
