# Generated by Django 3.1.13 on 2021-07-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0024_auto_20210728_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conservare',
            name='stare_icoanelor_istorice',
        ),
        migrations.RemoveField(
            model_name='conservare',
            name='stare_icoanelor_istorice_detalii',
        ),
        migrations.RemoveField(
            model_name='conservare',
            name='starea_mobilierului',
        ),
        migrations.RemoveField(
            model_name='conservare',
            name='starea_mobilierului_detalii',
        ),
        migrations.RemoveField(
            model_name='conservare',
            name='starea_obiectelor_de_cult',
        ),
        migrations.RemoveField(
            model_name='conservare',
            name='starea_obiectelor_de_cult_detalii',
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_bolti',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_bolti_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_cimitir',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_cimitir_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_corp_biserica',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_corp_biserica_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_elemente_arhitecturale',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_elemente_arhitecturale_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_finisaj_peste_corp',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_finisaj_peste_corp_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_finisaj_tambur_turn',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_finisaj_tambur_turn_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_fundatii',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_fundatii_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_icoane_istorice',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_icoane_istorice_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_invelitoare',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_invelitoare_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_monumente_funerare_valoroase',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_monumente_funerare_valoroase_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_pardoseli_interioare',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_pardoseli_interioare_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_picturi_exterioare',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_picturi_exterioare_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_picturi_interioare',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_picturi_interioare_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_sarpanta_peste_corp_biserica',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_sarpanta_peste_corp_biserica_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_structura_turn',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_structura_turn_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_teren',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_teren_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_usi_si_ferestre',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='stare_usi_si_ferestre_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='starea_mobilier',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='starea_mobilier_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='starea_obiecte_de_cult',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='starea_obiecte_de_cult_detalii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='vegetatie_invaziva',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conservare',
            name='vegetatie_invaziva_detalii',
            field=models.TextField(blank=True, null=True),
        ),
    ]
