# Generated by Django 3.1.13 on 2021-08-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biserici", "0026_componentaartistica_suport"),
    ]

    operations = [
        migrations.RenameField(
            model_name="componentaartistica",
            old_name="suport",
            new_name="suport_proscomidie",
        ),
    ]
