# Generated by Django 3.1.13 on 2021-07-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0026_auto_20210728_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservare',
            name='stare_structura_turn_detalii',
            field=models.TextField(blank=True, help_text='tarea structurii turnului, inclusiv a tălpilor și a coifului', null=True),
        ),
        migrations.AlterField(
            model_name='conservare',
            name='vegetatie_invaziva_detalii',
            field=models.TextField(blank=True, help_text='Vegetație invazivă ce poate pune monumentul în pericol', null=True),
        ),
    ]
