# Generated by Django 3.1.13 on 2021-07-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0027_auto_20210728_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patrimoniu',
            options={'verbose_name_plural': 'Valoare Patrimoniu'},
        ),
        migrations.AlterField(
            model_name='patrimoniu',
            name='vechime',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Printr-un algorim definit se va da automat o notă de la 1-5 în funcție de vechimea monumentului si a picturii descrise conform OMCC2682/2003 ETC', null=True),
        ),
    ]
