# Generated by Django 3.1.13 on 2021-08-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biserici", "0029_auto_20210803_1609"),
    ]

    operations = [
        migrations.RenameField(
            model_name="componentaartistica",
            old_name="iconostas_naos_altar_finisaj",
            new_name="iconostas_naos_altar_tehnica",
        ),
    ]
