# Generated by Django 3.1.13 on 2021-08-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomenclatoare", "0009_auto_20210803_1534"),
        ("biserici", "0031_auto_20210803_1618"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaldescriere",
            name="sarpanta_tip",
        ),
        migrations.RemoveField(
            model_name="descriere",
            name="sarpanta_tip",
        ),
        migrations.AddField(
            model_name="descriere",
            name="sarpanta_tip",
            field=models.ManyToManyField(blank=True, to="nomenclatoare.TipSarpanta", verbose_name="Șarpantă (tip)"),
        ),
    ]
