# Generated by Django 3.1.13 on 2021-08-03 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nomenclatoare", "0010_historicaltiparcbolta_tiparcbolta"),
        ("biserici", "0034_auto_20210803_1634"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="componentaartistica",
            name="altar_decor_detalii",
        ),
        migrations.RemoveField(
            model_name="componentaartistica",
            name="iconostas_pronaos_naos_finisaj",
        ),
        migrations.RemoveField(
            model_name="historicalcomponentaartistica",
            name="altar_decor_detalii",
        ),
        migrations.AddField(
            model_name="componentaartistica",
            name="altar_detalii",
            field=models.TextField(blank=True, null=True, verbose_name="Detalii"),
        ),
        migrations.AddField(
            model_name="componentaartistica",
            name="altar_piciorul_mesei",
            field=models.ManyToManyField(
                blank=True, related_name="piciorul_mesei", to="nomenclatoare.Material", verbose_name="Piciorul mesei"
            ),
        ),
        migrations.AddField(
            model_name="componentaartistica",
            name="altar_placa_mesei",
            field=models.ManyToManyField(
                blank=True, related_name="placa_mesei", to="nomenclatoare.Material", verbose_name="Placa mesei"
            ),
        ),
        migrations.AddField(
            model_name="componentaartistica",
            name="iconostas_pronaos_naos_tehnica",
            field=models.ManyToManyField(
                blank=True,
                related_name="iconostasuri_pronaos_naos",
                to="nomenclatoare.FinisajIconostas",
                verbose_name="Tehnica",
            ),
        ),
        migrations.AddField(
            model_name="finisaj",
            name="finisaj_exterior_observatii",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finisajactualinvelitoare",
            name="observatii",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finisajanteriorinvelitoare",
            name="observatii",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finisajinvelitoareturn",
            name="observatii",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finisajtamburturn",
            name="observatii",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcomponentaartistica",
            name="altar_detalii",
            field=models.TextField(blank=True, null=True, verbose_name="Detalii"),
        ),
        migrations.AddField(
            model_name="historicalfinisaj",
            name="finisaj_exterior_observatii",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalfinisajactualinvelitoare",
            name="observatii",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalfinisajanteriorinvelitoare",
            name="observatii",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalfinisajinvelitoareturn",
            name="observatii",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalfinisajtamburturn",
            name="observatii",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="componentaartistica",
            name="altar_decor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decoruri_altar",
                to="nomenclatoare.finisajiconostas",
                verbose_name="Decor",
            ),
        ),
        migrations.AlterField(
            model_name="componentaartistica",
            name="iconostas_naos_altar_tehnica",
            field=models.ManyToManyField(
                blank=True,
                related_name="iconostasuri_naos_altar",
                to="nomenclatoare.FinisajIconostas",
                verbose_name="Tehnică",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomponentaartistica",
            name="altar_decor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nomenclatoare.finisajiconostas",
                verbose_name="Decor",
            ),
        ),
    ]
