# Generated by Django 3.1.13 on 2021-08-03 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biserici', '0040_auto_20210803_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFotografieUrmeSemneSimboluri',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('poza', models.TextField(max_length=250)),
                ('detalii', models.TextField(blank=True, null=True)),
                ('copyright', models.CharField(blank=True, max_length=150, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fotografii', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='biserici.fotografii')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fotografie urme semne simboluri',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FotografieUrmeSemneSimboluri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poza', models.ImageField(max_length=250, upload_to='fotografii')),
                ('detalii', models.TextField(blank=True, null=True)),
                ('copyright', models.CharField(blank=True, max_length=150, null=True)),
                ('fotografii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biserici.fotografii')),
            ],
        ),
    ]
