# Generated by Django 3.1.13 on 2021-08-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0042_auto_20210803_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriere',
            name='masa_altar_observatii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldescriere',
            name='masa_altar_observatii',
            field=models.TextField(blank=True, null=True),
        ),
    ]
