# Generated by Django 3.1.13 on 2021-08-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0043_auto_20210803_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriere',
            name='observatii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descriere',
            name='turn_observatii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldescriere',
            name='observatii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldescriere',
            name='turn_observatii',
            field=models.TextField(blank=True, null=True),
        ),
    ]
