# Generated by Django 3.1.13 on 2021-08-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biserici", "0045_auto_20210804_1252"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalistoric",
            name="missing_fields",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="istoric",
            name="missing_fields",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
