# Generated by Django 3.1.13 on 2021-08-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0047_auto_20210804_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservare',
            name='missing_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalconservare',
            name='missing_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatrimoniu',
            name='missing_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patrimoniu',
            name='missing_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
