# Generated by Django 3.1.13 on 2021-08-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0049_auto_20210804_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentaartistica',
            name='completare',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcomponentaartistica',
            name='completare',
            field=models.FloatField(default=0),
        ),
    ]
