# Generated by Django 3.1.13 on 2021-09-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0051_auto_20210805_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriere',
            name='detalii_materiale',
            field=models.TextField(blank=True, help_text='Materialele care compun structura de rezistentă a bisericii', null=True),
        ),
        migrations.AlterField(
            model_name='historicaldescriere',
            name='detalii_materiale',
            field=models.TextField(blank=True, help_text='Materialele care compun structura de rezistentă a bisericii', null=True),
        ),
    ]
