# Generated by Django 3.1.13 on 2021-10-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0052_auto_20210916_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nume'),
        ),
    ]
