# Generated by Django 3.1.13 on 2022-07-19 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biserici', '0063_auto_20220719_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='IstoricNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scurt_istoric', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biserici.istoricscurtistoric', verbose_name='Scurt Istoric')),
            ],
        ),
        migrations.AddField(
            model_name='biserica',
            name='istoric_new',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='istoric_new', to='biserici.istoricnew'),
        ),
        migrations.AddField(
            model_name='historicalbiserica',
            name='istoric_new',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='biserici.istoricnew'),
        ),
    ]
