# Generated by Django 3.1.13 on 2022-07-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fragmente", "0008_auto_20220720_2038"),
        ("biserici", "0067_auto_20220721_1303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abturlecaracteristici",
            name="amplasare",
            field=models.ManyToManyField(blank=True, to="fragmente.AmplasareTurle"),
        ),
        migrations.AlterField(
            model_name="abturncaracteristici",
            name="amplasare",
            field=models.ManyToManyField(blank=True, to="fragmente.AmplasareTurn"),
        ),
        migrations.AlterField(
            model_name="abturncaracteristicigalerie",
            name="tip",
            field=models.ManyToManyField(blank=True, to="fragmente.TipGalerieTurn"),
        ),
        migrations.AlterField(
            model_name="abturnstructura",
            name="asezare",
            field=models.ManyToManyField(blank=True, to="fragmente.AsezareTalpiTurn"),
        ),
        migrations.AlterField(
            model_name="abturnstructura",
            name="relatie_talpi",
            field=models.ManyToManyField(blank=True, to="fragmente.RelatieTalpiTurn"),
        ),
        migrations.AlterField(
            model_name="reperegeograficezonenaturale",
            name="tip_zone",
            field=models.ManyToManyField(blank=True, to="fragmente.TipZoneNaturale", verbose_name="Tip Zone Naturale"),
        ),
    ]
