# Generated by Django 3.1.13 on 2022-07-21 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("fragmente", "0008_auto_20220720_2038"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("biserici", "0068_auto_20220721_1305"),
    ]

    operations = [
        migrations.CreateModel(
            name="CAElementeSculptateAlteDecoratii",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exista", models.BooleanField(default=False, verbose_name="Există")),
                ("observatii", models.TextField(blank=True, null=True, verbose_name="Observații")),
            ],
        ),
        migrations.CreateModel(
            name="CAGeneral",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sinteza", models.TextField(blank=True, null=True, verbose_name="Sinteză descriere")),
                (
                    "sinteza_conservare",
                    models.TextField(blank=True, null=True, verbose_name="Sinteză stare de conservare"),
                ),
                (
                    "sinteza_interventii",
                    models.TextField(blank=True, null=True, verbose_name="Sinteză intervenții în timp"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CAIconostas",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="CAIconostasComponente",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("observatii", models.TextField(blank=True, null=True, verbose_name="Observații")),
            ],
        ),
        migrations.CreateModel(
            name="CAIconostasMateriale",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("observatii", models.TextField(blank=True, null=True, verbose_name="Observații")),
            ],
        ),
        migrations.CreateModel(
            name="CAIconostasPictura",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("observatii", models.TextField(blank=True, null=True, verbose_name="Observații")),
            ],
        ),
        migrations.CreateModel(
            name="CAIconostasScultptura",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descriere", models.TextField(blank=True, null=True, verbose_name="Descriere")),
            ],
        ),
        migrations.CreateModel(
            name="CAIconostasTipologie",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("observatii", models.TextField(blank=True, null=True, verbose_name="Observații")),
            ],
        ),
        migrations.CreateModel(
            name="CAMobilierIstoric",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exista", models.BooleanField(default=False, verbose_name="Există")),
                ("observatii", models.TextField(blank=True, null=True, verbose_name="Observații")),
            ],
        ),
        migrations.CreateModel(
            name="CAMurala",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="CAObiecteDeCultIstorice",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exista", models.BooleanField(default=False, verbose_name="Există")),
                ("observatii", models.TextField(blank=True, null=True, verbose_name="Observații")),
            ],
        ),
        migrations.CreateModel(
            name="CAPereteNaosPronaos",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exista", models.BooleanField(default=False, verbose_name="Există")),
            ],
        ),
        migrations.AlterModelOptions(
            name="arhitecturabisericii",
            options={
                "ordering": ["biserica__the_order"],
                "verbose_name": "Arhitectura Bisericii",
                "verbose_name_plural": "Arhitectura Bisericii",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalarhitecturabisericii",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Arhitectura Bisericii",
                "verbose_name_plural": "historical Arhitectura Bisericii",
            },
        ),
        migrations.AlterField(
            model_name="abboltitavane",
            name="relatie_bolta_altar_naos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fragmente.relatieboltaaltarnaos",
                verbose_name="Relație Boltă Altar-Naos",
            ),
        ),
        migrations.AlterField(
            model_name="abcor",
            name="stare_conservare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.stareconservare",
                verbose_name="Stare Conservare",
            ),
        ),
        migrations.AlterField(
            model_name="abcorpgoluri",
            name="stare_conservare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.stareconservare",
                verbose_name="Stare conservare",
            ),
        ),
        migrations.AlterField(
            model_name="abcorppardoseala",
            name="stare_conservare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.stareconservare",
                verbose_name="Stare conservare",
            ),
        ),
        migrations.AlterField(
            model_name="abcorptalpi",
            name="stare_conservare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.stareconservare",
                verbose_name="Stare conservare",
            ),
        ),
        migrations.AlterField(
            model_name="abfundatiesoclu",
            name="fundatie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.abfundatiesoclufundatie",
                verbose_name="Fundație",
            ),
        ),
        migrations.AlterField(
            model_name="abfundatiesoclu",
            name="soclu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.abfundatiesoclusoclu",
                verbose_name="Soclu",
            ),
        ),
        migrations.AlterField(
            model_name="abfundatiesoclu",
            name="stare_conservare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.stareconservare",
                verbose_name="Stare conservare",
            ),
        ),
        migrations.AlterField(
            model_name="abfundatiesoclufundatie",
            name="materiale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.abfundatiesoclufundatiemateriale",
                verbose_name="Materiale",
            ),
        ),
        migrations.AlterField(
            model_name="abfundatiesoclufundatie",
            name="structura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.abfundatiesoclufundatiestructura",
                verbose_name="Structură",
            ),
        ),
        migrations.AlterField(
            model_name="abfundatiesoclusoclu",
            name="finisaje",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.abfundatiesoclusoclufinisaje",
                verbose_name="Materiale",
            ),
        ),
        migrations.AlterField(
            model_name="abfundatiesoclusoclu",
            name="materiale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.abfundatiesoclusoclumateriale",
                verbose_name="Materiale",
            ),
        ),
        migrations.AlterField(
            model_name="abfundatiesoclusoclu",
            name="structura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.abfundatiesoclusoclustructura",
                verbose_name="Structură",
            ),
        ),
        migrations.AlterField(
            model_name="abgeneral",
            name="planimetria_bisericii",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.abgeneralplanimetriabisericii",
                verbose_name="Planimetria bisericii",
            ),
        ),
        migrations.AlterField(
            model_name="abgeneralplanimetriabisericii",
            name="spatii_biserica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fragmente.spatiibiserica",
                verbose_name="Spații Biserică",
            ),
        ),
        migrations.AlterField(
            model_name="absarpantacorpbiserica",
            name="stare_conservare_invelitoare_sarpanta_corp_biserica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stare_conservare_invelitoare_sarpanta_corp_biserica",
                to="biserici.stareconservare",
                verbose_name="Stare conservare Învelitoare Șarpantă Corp Biserică",
            ),
        ),
        migrations.AlterField(
            model_name="absarpantacorpbiserica",
            name="stare_conservare_structura_sarpanta_corp_biserica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stare_conservare_structura_sarpanta_corp_biserica",
                to="biserici.stareconservare",
                verbose_name="Stare conservare Structură Șarpantă Corp Biserică",
            ),
        ),
        migrations.AlterField(
            model_name="abturle",
            name="stare_conservare_finisaje_turle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turle_stare_conservare_finisaje_turle",
                to="biserici.stareconservare",
                verbose_name="Stare conservare Finisaje Turn",
            ),
        ),
        migrations.AlterField(
            model_name="abturle",
            name="stare_conservare_structura_turle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turle_stare_conservare_structura_turle",
                to="biserici.stareconservare",
                verbose_name="Stare conservare Structură Turle",
            ),
        ),
        migrations.AlterField(
            model_name="abturn",
            name="stare_conservare_finisaje_turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turn_stare_conservare_finisaje_turn",
                to="biserici.stareconservare",
                verbose_name="Stare conservare Finisaje Turn",
            ),
        ),
        migrations.AlterField(
            model_name="abturn",
            name="stare_conservare_structura_turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turn_stare_conservare_structura_turn",
                to="biserici.stareconservare",
                verbose_name="Stare conservare Structură Turn",
            ),
        ),
        migrations.AlterField(
            model_name="arhitecturabisericii",
            name="bolti_tavane",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.abboltitavane",
                verbose_name="Bolți / Tavane",
            ),
        ),
        migrations.AlterField(
            model_name="arhitecturabisericii",
            name="cor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.abcor",
                verbose_name="Cor",
            ),
        ),
        migrations.AlterField(
            model_name="arhitecturabisericii",
            name="corp_biserica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.abcorp",
                verbose_name="Corp Biserică",
            ),
        ),
        migrations.AlterField(
            model_name="arhitecturabisericii",
            name="fundatie_soclu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.abfundatiesoclu",
                verbose_name="Fundație / Soclu",
            ),
        ),
        migrations.AlterField(
            model_name="arhitecturabisericii",
            name="general",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.abgeneral",
                verbose_name="General",
            ),
        ),
        migrations.AlterField(
            model_name="arhitecturabisericii",
            name="sarpanta_corp_biserica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.absarpantacorpbiserica",
                verbose_name="Șarpantă Corp Biserică",
            ),
        ),
        migrations.AlterField(
            model_name="arhitecturabisericii",
            name="turle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.abturle",
                verbose_name="Turle",
            ),
        ),
        migrations.AlterField(
            model_name="arhitecturabisericii",
            name="turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.abturn",
                verbose_name="Turn",
            ),
        ),
        migrations.AlterField(
            model_name="finisajinvelitoare",
            name="material",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="fragmente.materialinvelitoare"
            ),
        ),
        migrations.AlterField(
            model_name="identificare",
            name="frecventa_utilizarii",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.identificarefrecventautilizarii",
            ),
        ),
        migrations.AlterField(
            model_name="identificare",
            name="singularitate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.identificaresingularitate",
            ),
        ),
        migrations.AlterField(
            model_name="istoric",
            name="pisanie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.istoricpisanie",
                verbose_name="Pisanie",
            ),
        ),
        migrations.AlterField(
            model_name="istoric",
            name="scurt_istoric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.istoricscurtistoric",
                verbose_name="Scurt Istoric",
            ),
        ),
        migrations.AlterField(
            model_name="istoricscurtistoric",
            name="datare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.datare",
                verbose_name="Pisanie",
            ),
        ),
        migrations.AlterField(
            model_name="justificaredatare",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fragmente.justificaredatare",
                verbose_name="Justificare Datare",
            ),
        ),
        migrations.AlterField(
            model_name="localizare",
            name="adresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.localizareadresa",
                verbose_name="Adresă",
            ),
        ),
        migrations.AlterField(
            model_name="localizare",
            name="referinte_cadastrale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.localizarereferintecadastrale",
                verbose_name="Referințe Cadastrale",
            ),
        ),
        migrations.AlterField(
            model_name="localizare",
            name="regim_proprietate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.localizareregimuldeproprietate",
                verbose_name="Regimul de Proprietate",
            ),
        ),
        migrations.AlterField(
            model_name="localizare",
            name="unitati_teritoriale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.localizareunitatiteritoriale",
                verbose_name="Unități Teritoriale",
            ),
        ),
        migrations.AlterField(
            model_name="localizareadresa",
            name="coordonate_gps",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.localizareadresacoordonategps",
                verbose_name="Coordonate GPS",
            ),
        ),
        migrations.AlterField(
            model_name="peisaj",
            name="amplasament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.peisajamplasament",
                verbose_name="Pisanie",
            ),
        ),
        migrations.AlterField(
            model_name="peisaj",
            name="ansamblu_construit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.peisajansambluconstruit",
                verbose_name="Pisanie",
            ),
        ),
        migrations.AlterField(
            model_name="peisaj",
            name="peisaj_cultural",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.peisajpeisajcultural",
                verbose_name="Scurt Istoric",
            ),
        ),
        migrations.AlterField(
            model_name="peisajamplasament",
            name="loc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.peisajamplasamentloc",
                verbose_name="Loc",
            ),
        ),
        migrations.AlterField(
            model_name="peisajamplasament",
            name="relatia_cu_cimitirul",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.peisajamplasamentrelatiacucimitirul",
                verbose_name="Relația cu cimitirul",
            ),
        ),
        migrations.AlterField(
            model_name="peisajamplasament",
            name="stare_conservare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.stareconservare",
                verbose_name="Stare Conservare",
            ),
        ),
        migrations.AlterField(
            model_name="peisajamplasament",
            name="toponim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.peisajamplasamenttoponim",
                verbose_name="Toponim",
            ),
        ),
        migrations.AlterField(
            model_name="peisajamplasamentrelatiacucimitirul",
            name="tip_relatie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fragmente.tiprelatiecucimitirul",
            ),
        ),
        migrations.AlterField(
            model_name="peisajansambluconstruit",
            name="stare_conservare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.stareconservare",
                verbose_name="Stare Conservare",
            ),
        ),
        migrations.AlterField(
            model_name="peisajansambluconstruitelementarhitectural",
            name="tip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fragmente.tipelementarhitectural",
                verbose_name="Tip",
            ),
        ),
        migrations.AlterField(
            model_name="peisajansambluconstruitelementpeisaj",
            name="tip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fragmente.tipelementdepeisaj",
                verbose_name="Tip",
            ),
        ),
        migrations.AlterField(
            model_name="peisajpeisajcultural",
            name="cadru",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.peisajpeisajculturalcadru",
            ),
        ),
        migrations.AlterField(
            model_name="peisajpeisajcultural",
            name="patrimoniu_imaterial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.peisajpeisajculturalpatrimoniuimaterial",
                verbose_name="Patrimoniu Imaterial",
            ),
        ),
        migrations.AlterField(
            model_name="peisajpeisajculturalcadru",
            name="tip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fragmente.tipcadrupeisaj",
                verbose_name="Tip Cadru",
            ),
        ),
        migrations.AlterField(
            model_name="reperegeografice",
            name="forma_relief",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.reperegeograficeformarelief",
                verbose_name="Formă de relief",
            ),
        ),
        migrations.AlterField(
            model_name="reperegeografice",
            name="reper_hidrografic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.reperegeograficereperhidrografic",
                verbose_name="Reper Hidrografic",
            ),
        ),
        migrations.AlterField(
            model_name="reperegeografice",
            name="zone_naturale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.reperegeograficezonenaturale",
                verbose_name="Zone Naturale (Arii Protejate)",
            ),
        ),
        migrations.AlterField(
            model_name="stareconservare",
            name="nota",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="fragmente.notastareconservare"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalComponenteArtistice",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "biserica",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.biserica",
                    ),
                ),
                (
                    "elemente_sculptate_alte_decoratii",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.caelementesculptatealtedecoratii",
                        verbose_name="Elemente sculptate / alte decorații",
                    ),
                ),
                (
                    "general",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.cageneral",
                        verbose_name="General",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "icoane_istorice",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.existaobservatiiimagini",
                        verbose_name="Icoane Istorice",
                    ),
                ),
                (
                    "iconostas",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.caiconostas",
                        verbose_name="Iconostas",
                    ),
                ),
                (
                    "mobilier_istoric",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.camobilieristoric",
                        verbose_name="Mobilier Istoric",
                    ),
                ),
                (
                    "murala_exteroara",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.camurala",
                        verbose_name="Pictura/decorația murală exteroară",
                    ),
                ),
                (
                    "murala_interioara",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.camurala",
                        verbose_name="Pictura/decorația murală interioară",
                    ),
                ),
                (
                    "obiecte_de_cult_instrainate",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.existaobservatiiimagini",
                        verbose_name="Obiecte de cult înstrăinate",
                    ),
                ),
                (
                    "obiecte_de_cult_istorice",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.caobiectedecultistorice",
                        verbose_name="Obiecte de Cult Istorice",
                    ),
                ),
                (
                    "perete_naos_pronaos",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.caperetenaospronaos",
                        verbose_name="Componente artistice la peretele despărțitor naos-pronaos",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Decriere Componente Artistice",
                "verbose_name_plural": "historical Decriere Componente Artistice",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ComponenteArtistice",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "biserica",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="componente_artistice",
                        to="biserici.biserica",
                    ),
                ),
                (
                    "elemente_sculptate_alte_decoratii",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="biserici.caelementesculptatealtedecoratii",
                        verbose_name="Elemente sculptate / alte decorații",
                    ),
                ),
                (
                    "general",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="biserici.cageneral",
                        verbose_name="General",
                    ),
                ),
                (
                    "icoane_istorice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artistic_icoane_istorice",
                        to="biserici.existaobservatiiimagini",
                        verbose_name="Icoane Istorice",
                    ),
                ),
                (
                    "iconostas",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="biserici.caiconostas",
                        verbose_name="Iconostas",
                    ),
                ),
                (
                    "mobilier_istoric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="biserici.camobilieristoric",
                        verbose_name="Mobilier Istoric",
                    ),
                ),
                (
                    "murala_exteroara",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artistic_murala_exterioara",
                        to="biserici.camurala",
                        verbose_name="Pictura/decorația murală exteroară",
                    ),
                ),
                (
                    "murala_interioara",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artistic_murala_interioara",
                        to="biserici.camurala",
                        verbose_name="Pictura/decorația murală interioară",
                    ),
                ),
                (
                    "obiecte_de_cult_instrainate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artistic_obiecte_instrainate",
                        to="biserici.existaobservatiiimagini",
                        verbose_name="Obiecte de cult înstrăinate",
                    ),
                ),
                (
                    "obiecte_de_cult_istorice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="biserici.caobiectedecultistorice",
                        verbose_name="Obiecte de Cult Istorice",
                    ),
                ),
                (
                    "perete_naos_pronaos",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="biserici.caperetenaospronaos",
                        verbose_name="Componente artistice la peretele despărțitor naos-pronaos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decriere Componente Artistice",
                "verbose_name_plural": "Decriere Componente Artistice",
                "ordering": ["biserica__the_order"],
            },
        ),
        migrations.CreateModel(
            name="CAProportieSuprafata",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("observatii", models.TextField(blank=True, null=True, verbose_name="Observații")),
                ("imagini", models.ManyToManyField(blank=True, to="biserici.Fotografie")),
            ],
        ),
    ]
