# Generated by Django 3.1.13 on 2022-07-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fragmente", "0009_auto_20220721_1420"),
        ("biserici", "0069_auto_20220721_1420"),
    ]

    operations = [
        migrations.AddField(
            model_name="caproportiesuprafata",
            name="proportie_suprafata",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fragmente.proportiepicturamurala",
                verbose_name="Proporția de suprafață acoperită/vizibilă",
            ),
        ),
        migrations.AddField(
            model_name="caperetenaospronaos",
            name="datare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.datare",
                verbose_name="Datare",
            ),
        ),
        migrations.AddField(
            model_name="caperetenaospronaos",
            name="interventii",
            field=models.ManyToManyField(blank=True, to="biserici.Interventie", verbose_name="Intervenții"),
        ),
        migrations.AddField(
            model_name="caperetenaospronaos",
            name="justificare_datare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.justificaredatare",
                verbose_name="Justificare Datare",
            ),
        ),
        migrations.AddField(
            model_name="caperetenaospronaos",
            name="proportie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.caproportiesuprafata",
                verbose_name="Proporția de suprafață acoperită/vizibilă",
            ),
        ),
        migrations.AddField(
            model_name="caperetenaospronaos",
            name="sculptura_alte_decoratii",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.existaobservatiiimagini",
                verbose_name="Sculptură/alte decorații",
            ),
        ),
        migrations.AddField(
            model_name="caperetenaospronaos",
            name="stare_conservare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.stareconservare",
                verbose_name="Stare Conservare",
            ),
        ),
        migrations.AddField(
            model_name="caperetenaospronaos",
            name="tehnica",
            field=models.ManyToManyField(
                blank=True, to="fragmente.TehnicaPicturiiDecoratiei", verbose_name="Tehnica picturii/decorației"
            ),
        ),
        migrations.AddField(
            model_name="caobiectedecultistorice",
            name="denumire",
            field=models.ManyToManyField(blank=True, to="fragmente.ObiecteDeCultIstorice", verbose_name="Denumire"),
        ),
        migrations.AddField(
            model_name="caobiectedecultistorice",
            name="imagini",
            field=models.ManyToManyField(blank=True, to="biserici.Fotografie"),
        ),
        migrations.AddField(
            model_name="camurala",
            name="datare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.datare",
                verbose_name="Datare",
            ),
        ),
        migrations.AddField(
            model_name="camurala",
            name="interventii",
            field=models.ManyToManyField(blank=True, to="biserici.Interventie", verbose_name="Intervenții"),
        ),
        migrations.AddField(
            model_name="camurala",
            name="justificare_datare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.justificaredatare",
                verbose_name="Justificare Datare",
            ),
        ),
        migrations.AddField(
            model_name="camurala",
            name="proportie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fragmente.proportiepicturamurala",
                verbose_name="Proporția de suprafață acoperită/vizibilă",
            ),
        ),
        migrations.AddField(
            model_name="camurala",
            name="stare_conservare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.stareconservare",
                verbose_name="Stare Conservare",
            ),
        ),
        migrations.AddField(
            model_name="camurala",
            name="tehnica",
            field=models.ManyToManyField(
                blank=True, to="fragmente.TehnicaPicturiiDecoratiei", verbose_name="Tehnica picturii/decorației"
            ),
        ),
        migrations.AddField(
            model_name="camobilieristoric",
            name="denumire",
            field=models.ManyToManyField(blank=True, to="fragmente.MobilierIstoric", verbose_name="Denumire"),
        ),
        migrations.AddField(
            model_name="camobilieristoric",
            name="imagini",
            field=models.ManyToManyField(blank=True, to="biserici.Fotografie"),
        ),
        migrations.AddField(
            model_name="camobilieristoric",
            name="stare_conservare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.stareconservare",
                verbose_name="Stare Conservare",
            ),
        ),
        migrations.AddField(
            model_name="caiconostastipologie",
            name="imagini",
            field=models.ManyToManyField(blank=True, to="biserici.Fotografie"),
        ),
        migrations.AddField(
            model_name="caiconostastipologie",
            name="tip",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="fragmente.tipiconostas"
            ),
        ),
        migrations.AddField(
            model_name="caiconostasscultptura",
            name="imagini",
            field=models.ManyToManyField(blank=True, to="biserici.Fotografie"),
        ),
        migrations.AddField(
            model_name="caiconostaspictura",
            name="imagini",
            field=models.ManyToManyField(blank=True, to="biserici.Fotografie"),
        ),
        migrations.AddField(
            model_name="caiconostaspictura",
            name="proportie_suprafata",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fragmente.proportiepicturaiconostas",
                verbose_name="Proporția de suprafață acoperită",
            ),
        ),
        migrations.AddField(
            model_name="caiconostaspictura",
            name="tehnica",
            field=models.ManyToManyField(
                blank=True, to="fragmente.TehnicaPicturiiIconostasului", verbose_name="Tehnica Picturii"
            ),
        ),
        migrations.AddField(
            model_name="caiconostasmateriale",
            name="imagini",
            field=models.ManyToManyField(blank=True, to="biserici.Fotografie"),
        ),
        migrations.AddField(
            model_name="caiconostasmateriale",
            name="materiale",
            field=models.ManyToManyField(blank=True, to="fragmente.MaterialeIconostas"),
        ),
        migrations.AddField(
            model_name="caiconostascomponente",
            name="componente",
            field=models.ManyToManyField(blank=True, to="fragmente.ComponenteIconostas"),
        ),
        migrations.AddField(
            model_name="caiconostascomponente",
            name="imagini",
            field=models.ManyToManyField(blank=True, to="biserici.Fotografie"),
        ),
        migrations.AddField(
            model_name="caiconostas",
            name="componente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.caiconostascomponente",
                verbose_name="Componente",
            ),
        ),
        migrations.AddField(
            model_name="caiconostas",
            name="datare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.datare",
                verbose_name="Datare",
            ),
        ),
        migrations.AddField(
            model_name="caiconostas",
            name="interventii",
            field=models.ManyToManyField(blank=True, to="biserici.Interventie", verbose_name="Intervenții"),
        ),
        migrations.AddField(
            model_name="caiconostas",
            name="justificare_datare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.justificaredatare",
                verbose_name="Justificare Datare",
            ),
        ),
        migrations.AddField(
            model_name="caiconostas",
            name="materiale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.caiconostasmateriale",
                verbose_name="Materiale componente",
            ),
        ),
        migrations.AddField(
            model_name="caiconostas",
            name="pictura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.caiconostaspictura",
                verbose_name="Pictură",
            ),
        ),
        migrations.AddField(
            model_name="caiconostas",
            name="sculptura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.caiconostasscultptura",
                verbose_name="Sculptură/alte decorații",
            ),
        ),
        migrations.AddField(
            model_name="caiconostas",
            name="stare_conservare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.stareconservare",
                verbose_name="Stare Conservare",
            ),
        ),
        migrations.AddField(
            model_name="caiconostas",
            name="tipologie",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="biserici.caiconostastipologie"
            ),
        ),
        migrations.AddField(
            model_name="cageneral",
            name="foto_generale_exterior",
            field=models.ManyToManyField(
                blank=True, related_name="ca_foto_generale_exterior", to="biserici.Fotografie"
            ),
        ),
        migrations.AddField(
            model_name="cageneral",
            name="foto_generale_interior",
            field=models.ManyToManyField(
                blank=True, related_name="ca_foto_generale_interior", to="biserici.Fotografie"
            ),
        ),
        migrations.AddField(
            model_name="caelementesculptatealtedecoratii",
            name="imagini",
            field=models.ManyToManyField(blank=True, to="biserici.Fotografie"),
        ),
        migrations.AddField(
            model_name="caelementesculptatealtedecoratii",
            name="stare_conservare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biserici.stareconservare",
                verbose_name="Stare Conservare",
            ),
        ),
    ]
