# Generated by Django 3.1.13 on 2022-07-21 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("biserici", "0070_auto_20220721_1420"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiscuriInstalatii",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exista", models.BooleanField(default=False, verbose_name="Există")),
                ("descriere", models.TextField(blank=True, null=True, verbose_name="Descriere")),
                (
                    "ultima_interventie",
                    models.DateField(blank=True, null=True, verbose_name="Ultima Intervenție / Verificare"),
                ),
                ("risc", models.BooleanField(default=False, verbose_name="Risc")),
                ("observatii", models.TextField(blank=True, null=True, verbose_name="Observații")),
                ("imagini", models.ManyToManyField(blank=True, to="biserici.Fotografie")),
            ],
        ),
        migrations.CreateModel(
            name="InstalatiiEchipamente",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "biserica",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instalatii_echipamente",
                        to="biserici.biserica",
                    ),
                ),
                (
                    "instalatii_electrice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instalatii_electrice",
                        to="biserici.riscuriinstalatii",
                        verbose_name="Instalații electrice",
                    ),
                ),
                (
                    "instalatii_termice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instalatii_termice",
                        to="biserici.riscuriinstalatii",
                        verbose_name="Instalații Termice",
                    ),
                ),
                (
                    "monitorizare_antiefractie_si_vandalism",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitorizare_antiefractie_si_vandalism",
                        to="biserici.riscuriinstalatii",
                        verbose_name="Monitorizare Antiefracție și Vandalism",
                    ),
                ),
                (
                    "paratraznet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paratraznet",
                        to="biserici.riscuriinstalatii",
                        verbose_name="Paratrăznet",
                    ),
                ),
                (
                    "pichet_psi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pichet_psi",
                        to="biserici.riscuriinstalatii",
                        verbose_name="Pichet PSI",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instalații și Echipamente",
                "verbose_name_plural": "Instalații și Echipamente",
                "ordering": ["biserica__the_order"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalInstalatiiEchipamente",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "biserica",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.biserica",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instalatii_electrice",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.riscuriinstalatii",
                        verbose_name="Instalații electrice",
                    ),
                ),
                (
                    "instalatii_termice",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.riscuriinstalatii",
                        verbose_name="Instalații Termice",
                    ),
                ),
                (
                    "monitorizare_antiefractie_si_vandalism",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.riscuriinstalatii",
                        verbose_name="Monitorizare Antiefracție și Vandalism",
                    ),
                ),
                (
                    "paratraznet",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.riscuriinstalatii",
                        verbose_name="Paratrăznet",
                    ),
                ),
                (
                    "pichet_psi",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.riscuriinstalatii",
                        verbose_name="Pichet PSI",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Instalații și Echipamente",
                "verbose_name_plural": "historical Instalații și Echipamente",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
