# Generated by Django 3.1.13 on 2022-07-21 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("biserici", "0071_historicalinstalatiiechipamente_instalatiiechipamente_riscuriinstalatii"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalificativValoare",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "calificativ",
                    models.IntegerField(
                        blank=True, choices=[(1, "A"), (2, "B"), (3, "C")], help_text="Calificativ", null=True
                    ),
                ),
                ("observatii", models.TextField(blank=True, null=True, verbose_name="Observații")),
            ],
        ),
        migrations.CreateModel(
            name="Valoare",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completare", models.FloatField(default=0)),
                ("missing_fields", models.JSONField(blank=True, null=True)),
                (
                    "arhitecturala",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arhitecturala",
                        to="biserici.calificativvaloare",
                        verbose_name="Valoarea Arhitecturală ",
                    ),
                ),
                (
                    "bioculturala",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bioculturala",
                        to="biserici.calificativvaloare",
                        verbose_name="Valoarea Bioculturală",
                    ),
                ),
                (
                    "biserica",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="valoare", to="biserici.biserica"
                    ),
                ),
                (
                    "componente_artistice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="componente_artistice",
                        to="biserici.calificativvaloare",
                        verbose_name="Valoarea Componentelor artistice",
                    ),
                ),
                (
                    "folosinta_actuala",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="folosinta_actuala",
                        to="biserici.calificativvaloare",
                        verbose_name="Folosința Actuală",
                    ),
                ),
                (
                    "imateriala",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imateriala",
                        to="biserici.calificativvaloare",
                        verbose_name="Valoarea Imaterială",
                    ),
                ),
                (
                    "integritate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integritate",
                        to="biserici.calificativvaloare",
                        verbose_name="Integritate / Autenticitate",
                    ),
                ),
                (
                    "mestesug",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mestesug",
                        to="biserici.calificativvaloare",
                        verbose_name="Valoarea Meșteșugului",
                    ),
                ),
                (
                    "peisaj_cultural",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="peisaj_cultural",
                        to="biserici.calificativvaloare",
                        verbose_name="Valoarea Peisajului Cultural",
                    ),
                ),
                (
                    "potential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="potential",
                        to="biserici.calificativvaloare",
                        verbose_name="Potențial",
                    ),
                ),
                (
                    "relevanta_actuala",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relevanta_actuala",
                        to="biserici.calificativvaloare",
                        verbose_name="Relevanța Actuală pentru Comunitate",
                    ),
                ),
                (
                    "sit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sit",
                        to="biserici.calificativvaloare",
                        verbose_name="Valoarea Sitului",
                    ),
                ),
                (
                    "unicitate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unicitate",
                        to="biserici.calificativvaloare",
                        verbose_name="Unicitate",
                    ),
                ),
                (
                    "valoare_memoriala",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="valoare_memoriala",
                        to="biserici.calificativvaloare",
                        verbose_name="Valoare Memorial-Simbolică",
                    ),
                ),
                (
                    "vechime",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vechime",
                        to="biserici.calificativvaloare",
                        verbose_name="Vechime",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Valoare Patrimoniu Cultural",
                "ordering": ["biserica__the_order"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalValoare",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("completare", models.FloatField(default=0)),
                ("missing_fields", models.JSONField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "arhitecturala",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.calificativvaloare",
                        verbose_name="Valoarea Arhitecturală ",
                    ),
                ),
                (
                    "bioculturala",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.calificativvaloare",
                        verbose_name="Valoarea Bioculturală",
                    ),
                ),
                (
                    "biserica",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.biserica",
                    ),
                ),
                (
                    "componente_artistice",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.calificativvaloare",
                        verbose_name="Valoarea Componentelor artistice",
                    ),
                ),
                (
                    "folosinta_actuala",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.calificativvaloare",
                        verbose_name="Folosința Actuală",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "imateriala",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.calificativvaloare",
                        verbose_name="Valoarea Imaterială",
                    ),
                ),
                (
                    "integritate",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.calificativvaloare",
                        verbose_name="Integritate / Autenticitate",
                    ),
                ),
                (
                    "mestesug",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.calificativvaloare",
                        verbose_name="Valoarea Meșteșugului",
                    ),
                ),
                (
                    "peisaj_cultural",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.calificativvaloare",
                        verbose_name="Valoarea Peisajului Cultural",
                    ),
                ),
                (
                    "potential",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.calificativvaloare",
                        verbose_name="Potențial",
                    ),
                ),
                (
                    "relevanta_actuala",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.calificativvaloare",
                        verbose_name="Relevanța Actuală pentru Comunitate",
                    ),
                ),
                (
                    "sit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.calificativvaloare",
                        verbose_name="Valoarea Sitului",
                    ),
                ),
                (
                    "unicitate",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.calificativvaloare",
                        verbose_name="Unicitate",
                    ),
                ),
                (
                    "valoare_memoriala",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.calificativvaloare",
                        verbose_name="Valoare Memorial-Simbolică",
                    ),
                ),
                (
                    "vechime",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biserici.calificativvaloare",
                        verbose_name="Vechime",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical valoare",
                "verbose_name_plural": "historical Valoare Patrimoniu Cultural",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
