# Generated by Django 3.1.13 on 2022-07-21 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("biserici", "0072_calificativvaloare_historicalvaloare_valoare"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalvaloare",
            name="completare",
        ),
        migrations.RemoveField(
            model_name="historicalvaloare",
            name="missing_fields",
        ),
        migrations.RemoveField(
            model_name="valoare",
            name="completare",
        ),
        migrations.RemoveField(
            model_name="valoare",
            name="missing_fields",
        ),
        migrations.AlterField(
            model_name="identificare",
            name="biserica",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="identificare", to="biserici.biserica"
            ),
        ),
        migrations.AlterField(
            model_name="localizare",
            name="biserica",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="localizare", to="biserici.biserica"
            ),
        ),
    ]
