log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ":443"

  flower:
    address: ":5555"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "costi.bleotu@gmail.com"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    www-web-router:
      rule: "Host(`www.biserici-inlemnite.ro`)"
      entryPoints:
        - web
      middlewares:
        - redirect-www-to-non-www
      service: frontend

    www-web-secure-router:
      rule: "Host(`www.biserici-inlemnite.ro`)"
      entryPoints:
        - web-secure
      middlewares:
        - redirect-www-to-non-www
      service: frontend

    web-router:
      rule: "Host(`biserici-inlemnite.ro`)"
      entryPoints:
        - web
      middlewares:
        - redirect
        - csrf
      service: frontend

    web-secure-router:
      rule: "Host(`biserici-inlemnite.ro`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: frontend
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    media-router:
      rule: "(Host(`biserici-inlemnite.ro`) && PathPrefix(`/media`))"
      entryPoints:
        - web
      middlewares:
        - redirect
        - csrf
      service: media

    media-secure-router:
      rule: "(Host(`biserici-inlemnite.ro`) && PathPrefix(`/media`))"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: media
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    api-router:
      rule: "(Host(`biserici-inlemnite.ro`) && HeadersRegexp(`User-Agent`, `.*facebookexternalhit.*`)) || (Host(`biserici-inlemnite.ro`) && HeadersRegexp(`User-Agent`, `.*Twitterbot.*`)) || (Host(`biserici-inlemnite.ro`) && HeadersRegexp(`User-Agent`, `.*Googlebot.*`)) || (Host(`biserici-inlemnite.ro`) && HeadersRegexp(`User-Agent`, `.*Slackbot.*`)) || (Host(`biserici-inlemnite.ro`) && PathPrefix(`/api`)) || (Host(`biserici-inlemnite.ro`) && PathPrefix(`/admin`)) || (Host(`biserici-inlemnite.ro`) && PathPrefix(`/cms`)) || (Host(`biserici-inlemnite.ro`) && PathPrefix(`/static`))"
      entryPoints:
        - web
      middlewares:
        - redirect
        - csrf
      service: django

    api-secure-router:
      rule: "(Host(`biserici-inlemnite.ro`) && HeadersRegexp(`User-Agent`, `.*facebookexternalhit.*`)) || (Host(`biserici-inlemnite.ro`) && HeadersRegexp(`User-Agent`, `.*Twitterbot.*`)) || (Host(`biserici-inlemnite.ro`) && HeadersRegexp(`User-Agent`, `.*Googlebot.*`)) || (Host(`biserici-inlemnite.ro`) && HeadersRegexp(`User-Agent`, `.*Slackbot.*`)) || (Host(`biserici-inlemnite.ro`) && PathPrefix(`/api`)) || (Host(`biserici-inlemnite.ro`) && PathPrefix(`/admin`)) || (Host(`biserici-inlemnite.ro`) && PathPrefix(`/cms`)) || (Host(`biserici-inlemnite.ro`) && PathPrefix(`/static`))"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    flower-secure-router:
      rule: "Host(`biserici-inlemnite.ro`)"
      entryPoints:
        - flower
      service: flower
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

  middlewares:
    redirect:
      # https://docs.traefik.io/master/middlewares/redirectscheme/
      redirectScheme:
        scheme: https
        permanent: true
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]
    redirect-www-to-non-www:
      # Redirect a request from an url to another with regex matching and replacement
      redirectregex:
        # Apply a permanent redirection (HTTP 301)
        permanent: true
        # The regular expression to match and capture elements from the request URL
        regex: "^https?://www\\.(.+)"
        # How to modify the URL to have the new target URL
        replacement: "https://${1}"
  services:
    media:
      loadBalancer:
        servers:
          - url: http://media

    frontend:
      loadBalancer:
        servers:
          - url: http://frontend
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
