# Generated by Django 3.1.13 on 2021-11-04 14:56

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('nomenclatoare', '0029_elementbiserica_historicalelementbiserica'),
        ('app', '0098_auto_20211103_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisticetapeistoricevizibile',
            name='element',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.elementinteriorbiserica'),
        ),
        migrations.AlterField(
            model_name='bisericapage',
            name='datare_secol',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_biserici', to='nomenclatoare.secol'),
        ),
        migrations.AlterField(
            model_name='bisericapage',
            name='judet',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_biserici', to='nomenclatoare.judet', verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='bisericapage',
            name='localitate',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_biserici', to='nomenclatoare.localitate', verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='iconostas_naos_altar_tip',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_iconostasuri_naos_altar', to='nomenclatoare.tipiconostas', verbose_name='Tip'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='iconostas_pronaos_naos_materiale',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_iconostasuri_pronaos_naos', to='nomenclatoare.materialiconostas', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='iconostas_pronaos_naos_tip',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_iconostasuri_pronaos_naos', to='nomenclatoare.tipiconostas', verbose_name='Tip'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_exterioara_datare_secol',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_localizari_exterioare', to='nomenclatoare.secol', verbose_name='Datare secol'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_exterioara_localizare',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_localizari_exterioare', to='nomenclatoare.localizarepictura', verbose_name='Proporția de suprafață acoperită'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_exterioara_tehnica',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_localizari_exterioare', to='nomenclatoare.tehnicapictura', verbose_name='Tehnică'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_interioara_datare_secol',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_localizari_interioare', to='nomenclatoare.secol', verbose_name='Datare secol'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_interioara_localizare',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_localizari_interioare', to='nomenclatoare.localizarepictura', verbose_name='Proporția de suprafață acoperită'),
        ),
        migrations.AlterField(
            model_name='componentaartisticapage',
            name='pictura_interioara_tehnica_pictura',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tehnicapictura', verbose_name='Tehnică'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='amplasament',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.amplasamentbiserica'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='bolta_peste_altar',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici_bolta_peste_altar', to='nomenclatoare.boltapestealtar', verbose_name='Boltă peste altar'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='bolta_peste_altar_tip',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.tipboltapestealtar', verbose_name='Tip'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='bolta_peste_naos',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici_bolta_peste_naos', to='nomenclatoare.tipboltapronaos', verbose_name='Boltă peste naos'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='bolta_peste_pronaos',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici_bolta_peste_pronaos', to='nomenclatoare.tipboltapronaos', verbose_name='Boltă peste pronaos'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='fundatia',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.tipfundatie', verbose_name='Structura fundației'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_material',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inchidere_tambur', to='nomenclatoare.finisajinvelitoare', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrlia_esenta_lemnoasa',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inchidere_tambur_turn_sindrlia_esenta', to='nomenclatoare.esentalemnoasa', verbose_name='Șindrila (esență lemnoasă)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrlia_forma_botului',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inchidere_tambur_turn', to='nomenclatoare.tipbotsindrila', verbose_name='Șindrila (forma botului)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrlia_prelucrare',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inchidere_tambur_turn', to='nomenclatoare.tipprelucraresindrila', verbose_name='Șindrila (prelucrare)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrlia_tipul_de_batere',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inchidere_tambur_turn', to='nomenclatoare.tipbateresindrila', verbose_name='Șindrila (tipul de batere)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='inchidere_tambur_turn_sindrlia_tipul_prindere',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inchidere_tambur_turn', to='nomenclatoare.tipprinderesindrila', verbose_name='Șindrila (tipul de prindere)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='interventii_invelitoare_sindrlia_esenta_lemnoasa',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventii_invelitoare', to='nomenclatoare.esentalemnoasa', verbose_name='Esența lemnoasă'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='interventii_invelitoare_sindrlia_forma_botului',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventii_invelitoare', to='nomenclatoare.tipbotsindrila', verbose_name='Forma botului'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='interventii_invelitoare_sindrlia_tipul_de_batere',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventii_invelitoare', to='nomenclatoare.tipbateresindrila', verbose_name='Tipul de batere'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_corp_material',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_corp', to='nomenclatoare.finisajinvelitoare', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrlia_esenta_lemnoasa',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_corp_sindrlia_esenta', to='nomenclatoare.esentalemnoasa', verbose_name='Șindrila (esență lemnoasă)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrlia_forma_botului',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_corp', to='nomenclatoare.tipbotsindrila', verbose_name='Șindrila (forma botului)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrlia_prelucrare',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_corp', to='nomenclatoare.tipprelucraresindrila', verbose_name='Șindrila (prelucrare)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrlia_tipul_de_batere',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_corp', to='nomenclatoare.tipbateresindrila', verbose_name='Șindrila (tipul de batere)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_corp_sindrlia_tipul_prindere',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_corp', to='nomenclatoare.tipprinderesindrila', verbose_name='Șindrila (tipul de prindere)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrlia_esenta_lemnoasa',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turle_sindrlia_esenta', to='nomenclatoare.esentalemnoasa', verbose_name='Șindrila (esență lemnoasă)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrlia_forma_botului',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turle', to='nomenclatoare.tipbotsindrila', verbose_name='Șindrila (forma botului)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrlia_prelucrare',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turle', to='nomenclatoare.tipprelucraresindrila', verbose_name='Șindrila (prelucrare)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrlia_tipul_de_batere',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turle', to='nomenclatoare.tipbateresindrila', verbose_name='Șindrila (tipul de batere)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_turle_sindrlia_tipul_prindere',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turle', to='nomenclatoare.tipprinderesindrila', verbose_name='Șindrila (tipul de prindere)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_turn_material',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turn', to='nomenclatoare.finisajinvelitoare', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrlia_esenta_lemnoasa',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turn_sindrlia_esenta', to='nomenclatoare.esentalemnoasa', verbose_name='Șindrila (esență lemnoasă)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrlia_forma_botului',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turn', to='nomenclatoare.tipbotsindrila', verbose_name='Șindrila (forma botului)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrlia_prelucrare',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turn', to='nomenclatoare.tipprelucraresindrila', verbose_name='Șindrila (prelucrare)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrlia_tipul_de_batere',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turn', to='nomenclatoare.tipbateresindrila', verbose_name='Șindrila (tipul de batere)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='invelitoare_turn_sindrlia_tipul_prindere',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invelitoare_turn', to='nomenclatoare.tipprinderesindrila', verbose_name='Șindrila (tipul de prindere)'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='materiale',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Materiale folosite in construcția bisericii', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.materialestructura'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='planimetria_bisericii',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='relatia_cu_cimitirul',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.relatiecimitir'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='sarpanta_material_cruci',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_material_cruci', to='nomenclatoare.materialcruci', verbose_name='Material cruci'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='sistem_in_catei',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.tipstructuracatei', verbose_name='Tip'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='sistem_in_cheotoare',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.tipstructuracheotoare', verbose_name='Tip'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='sistem_structural',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.tipsistemstructural', verbose_name='Tip'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='tiranti_tip',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.tiptiranti', verbose_name='Tip Tiranți'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='topografie',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.topografiebiserica'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='turle_stil',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biserici', to='nomenclatoare.stilturle', verbose_name='Stilul turlelor'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='turn_amplasare',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.amplasareturn', verbose_name='Amplasare'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='turn_asezare_talpi',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.asezaretalpaturn', verbose_name='Așezarea tălpilor turnului în legătură cu corpul bisericii'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='turn_dimensiune',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.dimensiuneturn', verbose_name='Dimensiune'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='turn_galerie',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.galerieturn', verbose_name='Galerie'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='turn_plan',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.planturn', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='turn_relatie_talpi',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.relatietalpaturn', verbose_name='Relația dintre tălpile turnului'),
        ),
        migrations.AlterField(
            model_name='descrierepage',
            name='turn_tip',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.tipturn', verbose_name='Tip'),
        ),
        migrations.AlterField(
            model_name='elementeansambluconstruit',
            name='element',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.elementansambluconstruit'),
        ),
        migrations.AlterField(
            model_name='elementeimportanteansambluconstruit',
            name='element',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.elementimportant'),
        ),
        migrations.AlterField(
            model_name='etapeistoricevizibile',
            name='element',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.elementbiserica'),
        ),
        migrations.AlterField(
            model_name='finisajealtar',
            name='element',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.elementinteriorbiserica'),
        ),
        migrations.AlterField(
            model_name='finisajealtar',
            name='material',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.finisaj'),
        ),
        migrations.AlterField(
            model_name='finisajenaos',
            name='element',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.elementinteriorbiserica'),
        ),
        migrations.AlterField(
            model_name='finisajenaos',
            name='material',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.finisaj'),
        ),
        migrations.AlterField(
            model_name='finisajeportic',
            name='element',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.elementinteriorbiserica'),
        ),
        migrations.AlterField(
            model_name='finisajeportic',
            name='material',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.finisaj'),
        ),
        migrations.AlterField(
            model_name='finisajepronaos',
            name='element',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatoare.elementinteriorbiserica'),
        ),
        migrations.AlterField(
            model_name='finisajepronaos',
            name='material',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomenclatoare.finisaj'),
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='cult',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.cultbiserica'),
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='functiune',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.functiunebiserica'),
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='functiune_initiala',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici_initiale', to='nomenclatoare.functiunebiserica'),
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='hram',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.hram'),
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='judet',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppp_biserici', to='nomenclatoare.judet', verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='localitate',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.localitate', verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='proprietate_actuala',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici_initiale', to='nomenclatoare.regimproprietate'),
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='singularitate',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.singularitatebiserica'),
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='statut',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.statutbiserica'),
        ),
        migrations.AlterField(
            model_name='identificarepage',
            name='utilizare',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.utilizarebiserica'),
        ),
        migrations.AlterField(
            model_name='istoricpage',
            name='datare_secol',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici', to='nomenclatoare.secol'),
        ),
        migrations.AlterField(
            model_name='istoricpage',
            name='studiu_dendocronologic_fisier',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Fișier'),
        ),
        migrations.AlterField(
            model_name='mutaribiserica',
            name='localitate',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_biserici_mutari', to='nomenclatoare.localitate'),
        ),
        migrations.AlterField(
            model_name='parteneriproiect',
            name='logo',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeaccese',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozealtar',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozealteelementeimportante',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeamplasament',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeartisticetapeistoricevizibile',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozebiserica',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozebolti',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeclopot',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeclopote',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozecor',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozecorpbiserica',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozecosoroabe',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozectitori',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozedescrierebolti',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeelementansambluconstruit',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeelementearhitecturale',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeelementesculptate',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeelementimportantansambluconstruit',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeetapeanterioareinvelitoare',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeetapeistoricevizibile',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeferestre',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozefinisajaltar',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozefinisajeexteriorcorp',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozefinisajeinchideretambur',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozefinisajeinvelitoare',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozefinisajeinvelitoareturle',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozefinisajeinvelitoareturn',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozefinisajexterior',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozefinisajnaos',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozefinisajperetiinteriori',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozefinisajportic',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozefinisajpronaos',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozefinisajtavanesibolti',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozefundatie',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozefundatii',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozegeneraleexterior',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozegeneraleinterior',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeicoanevechi',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeiconostas',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeinstalatieelectrica',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeinstalatietermica',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeinvelitoaresarpantasiturn',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozemasaatlar',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozemesteri',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozemobilier',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozemobiliere',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeobiectedecult',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeobiectedecultconservare',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeobiecteinstrainate',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeochiesi',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeparatraznet',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozepardoseliinterioare',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozepeisagisticasitului',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeperetedespartitor',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozepersonalitati',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozepicturaexterioara',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozepicturainterioara',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozepisanie',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeproscomidie',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozesarpanta',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozesarpantacorpbiserica',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozesit',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozesolee',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozestratpictural',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozestructuracatei',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozestructuracheotoare',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozestructuramixt',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozetalpi',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozetamplarii',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeteren',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozetiranti',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeturle',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeturn',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozeturnconservare',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozevegetatie',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozezonadinjurulbiserici',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='pozezugravi',
            name='poza',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
